### ISSUE TITLE
phn.ph_link.phn_prev and phn.ph_link.phn_next is zero , but attempt to access them!

### ISSUE THREAD

**Issue by flyinghare** [jemalloc/jemalloc#1108]
## In the following code, the error occurred at '!!!' . (I have expanded the macro 'ph_gen' in file 'extent.c' before build it):

```
...
 void
extent_heap_remove(extent_heap_t *ph, extent_t *phn)
{
...

	/* Find a possible replacement node, and link to parent. */
	ph_merge_children(extent_t, ph_link, phn, extent_ad_comp, replace);
	/* Set next/prev for sibling linked list. */
	if (replace != NULL) {
		if (parent != NULL) {
			phn_prev_set(extent_t, ph_link, replace, parent);
			phn_lchild_set(extent_t, ph_link, parent,
			    replace);
		} else {
			phn_prev_set(extent_t, ph_link, replace,
			    phn_prev_get(extent_t, ph_link, phn));
			if (phn_prev_get(extent_t, ph_link, phn) !=
			    NULL) {
				phn_next_set(extent_t, ph_link,
				    phn_prev_get(extent_t, ph_link, phn),
				    replace);
			}
		}
		phn_next_set(extent_t, ph_link, replace,
		    phn_next_get(extent_t, ph_link, phn));
		if (phn_next_get(extent_t, ph_link, phn) != NULL) {
			phn_prev_set(extent_t, ph_link,
			    phn_next_get(extent_t, ph_link, phn),
			    replace);
		}
	} else {
		if (parent != NULL) {
			extent_t *next = phn_next_get(extent_t, ph_link,
			    phn);
			phn_lchild_set(extent_t, ph_link, parent, next);
			if (next != NULL) {
				phn_prev_set(extent_t, ph_link, next,
				    parent);
			}
		} else {
			assert(phn_prev_get(extent_t, ph_link, phn) !=
			    NULL);
			phn_next_set(extent_t, ph_link,
				phn_prev_get(extent_t, ph_link, phn),   /* !!! error : phn.ph_link.phn_prev is zero*/
			    phn_next_get(extent_t, ph_link, phn));  /* !!! error : phn.ph_link.phn_next is zero*/
		}
		if (phn_next_get(extent_t, ph_link, phn) != NULL) {
			phn_prev_set(extent_t, ph_link,
			    phn_next_get(extent_t, ph_link, phn),
			    phn_prev_get(extent_t, ph_link, phn));
		}
	}
...	
```

## When the error occurred, value of phn is:
```

(gdb) p *phn
$2 = {
  e_arena = 0x7fb7531fe0c0, 
  e_addr = 0x7fb725dd7000, 
  e_size = 135168, 
  e_usize = 114688, 
  e_active = false, 
  e_zeroed = false, 
  e_committed = true, 
  e_slab = false, 
  {
    e_slab_data = {
      binind = 33, 
      nfree = 2, 
      bitmap = {3, 0, 0, 0, 0, 0, 0, 0}
    }, 
    {
      e_prof_tctx_pun = 0x200000021, 
      e_prof_tctx = 0x200000021
    }
  }, 
  qr_link = {
    qre_next = 0x7fb7287efb40, 
    qre_prev = 0x7fb7531ffa38
  }, 
  {
    ph_link = {
      phn_prev = 0x0, 
      phn_next = 0x0, 
      phn_lchild = 0x0
    }, 
    ql_link = {
      qre_next = 0x0, 
      qre_prev = 0x0
    }
  }
}

```

## When the error occurred, the stack is:
```

#0  0x000000000045248c in je_extent_heap_remove (ph=<optimized out>, phn=0x7fb7296cef00) at src/extent.c:320
#1  0x00000000004563b0 in extent_recycle (tsdn=tsdn@entry=0x7fb75a90b580, arena=arena@entry=0x7fb75032d3c0, 
    r_extent_hooks=r_extent_hooks@entry=0x7fb75a9081c0, extent_heaps=extent_heaps@entry=0x7fb75032f4a8, 
    cache=cache@entry=true, new_addr=new_addr@entry=0x7fb725dd7700, usize=32768, pad=0, alignment=64, zero=0x7fb75a9081be, 
    commit=0x7fb75a9080f7, slab=false) at src/extent.c:564
#2  0x0000000000456d2c in je_extent_alloc_cache (tsdn=tsdn@entry=0x7fb75a90b580, arena=arena@entry=0x7fb75032d3c0, 
    r_extent_hooks=r_extent_hooks@entry=0x7fb75a9081c0, new_addr=new_addr@entry=0x7fb725dd7700, usize=usize@entry=32768, 
    pad=pad@entry=0, alignment=64, zero=0x7fb75a9081be, slab=false) at src/extent.c:694
#3  0x000000000043bb03 in arena_extent_cache_alloc_locked (slab=false, zero=0x7fb75a9081be, alignment=64, pad=0, 
    usize=32768, new_addr=0x7fb725dd7700, r_extent_hooks=0x7fb75a9081c0, arena=0x7fb75032d3c0, tsdn=0x7fb75a90b580)
    at src/arena.c:63
#4  je_arena_extent_cache_alloc (tsdn=tsdn@entry=0x7fb75a90b580, arena=arena@entry=0x7fb75032d3c0, 
    r_extent_hooks=r_extent_hooks@entry=0x7fb75a9081c0, new_addr=0x7fb725dd7700, size=size@entry=32768, 
    alignment=alignment@entry=64, zero=0x7fb75a9081be) at src/arena.c:75
#5  0x0000000000458354 in large_ralloc_no_move_expand (tsdn=0x7fb75a90b580, extent=extent@entry=0x7fb734fbc6c0, 
    usize=usize@entry=65536, zero=<optimized out>) at src/large.c:145
#6  0x0000000000459134 in je_large_ralloc_no_move (zero=<optimized out>, usize_max=65536, usize_min=65536, 
    extent=0x7fb734fbc6c0, tsdn=0x7fb75a90b580) at src/large.c:205
#7  je_large_ralloc (tsdn=tsdn@entry=0x7fb75a90b580, arena=0x0, extent=extent@entry=0x7fb734fbc6c0, usize=usize@entry=65536, 
    alignment=alignment@entry=0, zero=<optimized out>, tcache=0x7fb74ff7e840) at src/large.c:264
#8  0x000000000043e3bd in je_arena_ralloc (tsdn=0x7fb75a90b580, arena=arena@entry=0x0, extent=extent@entry=0x7fb734fbc6c0, 
    ptr=ptr@entry=0x7fb725dce700, oldsize=oldsize@entry=32768, size=size@entry=65536, alignment=0, zero=false, 
    tcache=0x7fb74ff7e840) at src/arena.c:1567
#9  0x00000000004356b3 in je_iralloct (arena=0x0, tcache=<optimized out>, zero=false, alignment=0, size=65536, 
    oldsize=<optimized out>, ptr=0x7fb725dce700, extent=<optimized out>, tsdn=<optimized out>)
    at include/jemalloc/internal/jemalloc_internal.h:1163
#10 je_iralloc (zero=false, alignment=0, size=65536, oldsize=<optimized out>, ptr=0x7fb725dce700, extent=<optimized out>, 
    tsd=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1172
#11 je_realloc (ptr=0x7fb725dce700, size=65536) at src/jemalloc.c:1796
#12 0x0000000000420e61 in resizebox ()
#13 0x000000000042154a in luaL_prepbuffsize ()
#14 0x0000000000421615 in luaL_addlstring.part.2 ()
#15 0x00007fb755e89ed6 in pop_lstring (L=L@entry=0x7fb7507eb548, sb=sb@entry=0x7fb74ff8e2a8, sz=71, skip=skip@entry=0)
    at lualib-src/lua-socket.c:185
#16 0x00007fb755e8a1ec in lpopbuffer (L=0x7fb7507eb548) at lualib-src/lua-socket.c:242
#17 0x0000000000412f5f in luaD_precall ()
#18 0x000000000041e7be in luaV_execute ()
#19 0x00000000004131f0 in unroll ()
#20 0x000000000041277c in luaD_rawrunprotected ()
#21 0x00000000004133f0 in lua_resume ()
#22 0x00000000004268f7 in auxresume ()
#23 0x0000000000426c27 in luaB_coresume ()
#24 0x0000000000412f5f in luaD_precall ()
#25 0x000000000041e7be in luaV_execute ()
#26 0x000000000041333f in luaD_call ()
#27 0x0000000000413391 in luaD_callnoyield ()
#28 0x000000000041277c in luaD_rawrunprotected ()
#29 0x00000000004135dd in luaD_pcall ()
#30 0x000000000041097c in lua_pcallk ()
#31 0x0000000000425b00 in luaB_pcall ()
#32 0x0000000000412f5f in luaD_precall ()
#33 0x000000000041e7be in luaV_execute ()
#34 0x000000000041333f in luaD_call ()
---Type <return> to continue, or q <return> to quit---
#35 0x0000000000413391 in luaD_callnoyield ()
#36 0x000000000041277c in luaD_rawrunprotected ()
#37 0x00000000004135dd in luaD_pcall ()
#38 0x000000000041097c in lua_pcallk ()
#39 0x00007fb757900df8 in _cb (context=0x7fb75fd307c0, ud=0x7fb75fc49a08, type=6, session=0, source=0, msg=0x7fb73369e640, 
    sz=24) at lualib-src/lua-skynet.c:50
#40 0x0000000000408dea in dispatch_message (ctx=ctx@entry=0x7fb75fd307c0, msg=msg@entry=0x7fb75a90ad40)
    at skynet-src/skynet_server.c:259
#41 0x0000000000409964 in skynet_context_message_dispatch (sm=sm@entry=0x7fb75fe29880, q=q@entry=0x7fb7562ac180, 
    weight=weight@entry=-1) at skynet-src/skynet_server.c:313
#42 0x000000000040a09d in thread_worker (p=<optimized out>) at skynet-src/skynet_start.c:162
#43 0x00007fb75f9fe6ba in start_thread (arg=0x7fb75a90b700) at pthread_create.c:333
#44 0x00007fb75f01f3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by davidtgoldblatt** [comment]
This sort of error almost always indicates a memory corruption bug in the calling program; a good first step would be to try re-running your application under ASAN to try to catch the issue there.

**Comment by flyinghare** [comment]
Thank you. I'll try it first.

**Comment by interwq** [comment]
Closing assume resolved. Please reopen if otherwise.
