### ISSUE TITLE
hang in malloc_mutex_lock with some qt applications

### ISSUE THREAD

**Issue by justanerd** [jemalloc/jemalloc#1187]
Some QT Applications start randomly to hang when using jemalloc.
This is with the latest dev from github.
But also happens with 5.0.1.

config is:
```
autogen            : 0
debug              : 0
stats              : 1
prof               : 0
prof-libunwind     : 0
prof-libgcc        : 0
prof-gcc           : 0
fill               : 1
utrace             : 0
xmalloc            : 1
log                : 0
lazy_lock          : 1
cache-oblivious    : 1
cxx                : 1

```

```
(gdb) bt
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f43efadee73 in __GI___pthread_mutex_lock (mutex=0x7f43e9c055f8) at ../nptl/pthread_mutex_lock.c:85
#2  0x00007f43f1a13efa in malloc_mutex_lock_final (mutex=0x7f43e9c055b8) at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/include/jemalloc/internal/mutex.h:141
#3  je_malloc_mutex_lock_slow (mutex=mutex@entry=0x7f43e9c055b8) at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/src/mutex.c:84
#4  0x00007f43f1a259c4 in malloc_mutex_lock (mutex=0x7f43e9c055b8, tsdn=0x7f43e9eb2880)
    at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/include/jemalloc/internal/mutex.h:205
#5  je_tcache_bin_flush_small (tsd=tsd@entry=0x7f43e9eb2880, tcache=tcache@entry=0x7f43e9eb2a40, tbin=<optimized out>, binind=12, rem=16)
    at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/src/tcache.c:134
#6  0x00007f43f19e79d5 in tcache_dalloc_small (slow_path=false, binind=<optimized out>, ptr=0x7f43be911600, tcache=0x7f43e9eb2a40, tsd=<optimized out>)
    at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/include/jemalloc/internal/tcache_inlines.h:178
#7  arena_sdalloc (slow_path=false, alloc_ctx=0x0, tcache=0x7f43e9eb2a40, size=<optimized out>, ptr=0x7f43be911600, tsdn=<optimized out>)
    at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/include/jemalloc/internal/arena_inlines_b.h:336
#8  isdalloct (slow_path=false, alloc_ctx=0x0, tcache=0x7f43e9eb2a40, size=<optimized out>, ptr=0x7f43be911600, tsdn=<optimized out>)
    at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/include/jemalloc/internal/jemalloc_internal_inlines_c.h:131
#9  isfree (slow_path=false, tcache=0x7f43e9eb2a40, usize=<optimized out>, ptr=0x7f43be911600, tsd=0x7f43e9eb2880)
    at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/src/jemalloc.c:2280
#10 sdallocx (ptr=0x7f43be911600, size=<optimized out>, flags=<optimized out>) at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/src/jemalloc.c:3017
#11 0x00007f43f01e6b6a in QScopedPointerDeleter<QObjectData>::cleanup(QObjectData*) () at ../../include/QtCore/../../src/corelib/tools/qscopedpointer.h:60
#12 QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::~QScopedPointer() () at ../../include/QtCore/../../src/corelib/tools/qscopedpointer.h:107
#13 QObject::~QObject() (this=this@entry=0x7f43be8fce00) at kernel/qobject.cpp:882
#14 0x00007f43f12cb370 in QQmlTimer::~QQmlTimer() [clone .lto_priv.2757] () at ../../include/QtQml/5.10.1/QtQml/private/../../../../../src/qml/types/qqmltimer_p.h:63
#15 __base_dtor  (this=0x7f43be8fce00) at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#16 __deleting_dtor  (this=0x7f43be8fce00) at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#17 0x00007f43f01d983d in QObjectPrivate::deleteChildren() (this=0x7f43be8ff180) at kernel/qobject.cpp:1993
#18 0x00007f43f01e6b2b in QObject::~QObject() (this=this@entry=0x7f43be8fc080) at kernel/qobject.cpp:1023
#19 0x00007f43f16b0c82 in QQuickItem::~QQuickItem() (this=this@entry=0x7f43be8fc080) at items/qquickitem.cpp:2371
#20 0x00007f43f16b755a in QQuickFocusScope::~QQuickFocusScope() (this=0x7f43be8fc080) at items/qquickfocusscope.cpp:65
#21 __base_dtor  () at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#22 __deleting_dtor  (this=0x7f43be8fc080) at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#23 0x00007f43f13b6ddf in QQmlDelegateModel::~QQmlDelegateModel() (this=0x7f43e5acd220) at types/qqmldelegatemodel.cpp:269
#24 0x00007f43f13b6e49 in QQmlDelegateModel::~QQmlDelegateModel() (this=0x7f43e5acd220) at types/qqmldelegatemodel.cpp:284
#25 0x00007f43f16ed2dc in __base_dtor  (this=0x7f43be86c500) at items/qquickrepeater.cpp:65
#26 0x00007f43f16ed329 in __deleting_dtor  (this=0x7f43be86c500) at items/qquickrepeater.cpp:66
#27 0x00007f43f01e6b6a in QScopedPointerDeleter<QObjectData>::cleanup(QObjectData*) () at ../../include/QtCore/../../src/corelib/tools/qscopedpointer.h:60
#28 QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::~QScopedPointer() () at ../../include/QtCore/../../src/corelib/tools/qscopedpointer.h:107
#29 QObject::~QObject() (this=this@entry=0x7f43be8dedc0) at kernel/qobject.cpp:882
#30 0x00007f43f16b0c82 in QQuickItem::~QQuickItem() (this=this@entry=0x7f43be8dedc0) at items/qquickitem.cpp:2371
#31 0x00007f43f16b7a7a in QQuickRepeater::~QQuickRepeater() (this=0x7f43be8dedc0) at items/qquickrepeater.cpp:163
#32 __base_dtor  () at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#33 __deleting_dtor  (this=0x7f43be8dedc0) at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#34 0x00007f43f01d983d in QObjectPrivate::deleteChildren() (this=0x7f43be86c380) at kernel/qobject.cpp:1993
#35 0x00007f43f01e6b2b in QObject::~QObject() (this=this@entry=0x7f43be8b8340) at kernel/qobject.cpp:1023
#36 0x00007f43f16b0c82 in QQuickItem::~QQuickItem() (this=this@entry=0x7f43be8b8340) at items/qquickitem.cpp:2371
#37 0x00007f43f177b1db in QQuickImplicitSizeItem::~QQuickImplicitSizeItem() [clone .lto_priv.2769] () at items/qquickimplicitsizeitem_p.h:60
#38 QQuickBasePositioner::~QQuickBasePositioner() (this=this@entry=0x7f43be8b8340) at items/qquickpositioners.cpp:168
#39 0x00007f43f16cc47a in QQuickRow::~QQuickRow() [clone .lto_priv.4489] () at items/qquickpositioners_p.h:244
#40 __base_dtor  () at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#41 __deleting_dtor  (this=0x7f43be8b8340) at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#42 0x00007f43f01d983d in QObjectPrivate::deleteChildren() (this=0x7f43be8fe000) at kernel/qobject.cpp:1993
#43 0x00007f43f01e6b2b in QObject::~QObject() (this=this@entry=0x7f43be8ddd40) at kernel/qobject.cpp:1023
#44 0x00007f43f16b0c82 in QQuickItem::~QQuickItem() (this=this@entry=0x7f43be8ddd40) at items/qquickitem.cpp:2371
#45 0x00007f43f16b76a5 in __base_dtor  () at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#46 __deleting_dtor  (this=0x7f43be8ddd40) at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#47 0x00007f43f01d983d in QObjectPrivate::deleteChildren() (this=0x7f43be8b0080) at kernel/qobject.cpp:1993
#48 0x00007f43f01e6b2b in QObject::~QObject() (this=this@entry=0x7f43be8dd500) at kernel/qobject.cpp:1023
#49 0x00007f43f16b0c82 in QQuickItem::~QQuickItem() (this=this@entry=0x7f43be8dd500) at items/qquickitem.cpp:2371
#50 0x00007f43f16b76a5 in __base_dtor  () at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#51 __deleting_dtor  (this=0x7f43be8dd500) at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#52 0x00007f43f01d983d in QObjectPrivate::deleteChildren() (this=0x7f43be732380) at kernel/qobject.cpp:1993
#53 0x00007f43f01e6b2b in QObject::~QObject() (this=this@entry=0x7f43be8dca80) at kernel/qobject.cpp:1023
#54 0x00007f43f16b0c82 in QQuickItem::~QQuickItem() (this=this@entry=0x7f43be8dca80) at items/qquickitem.cpp:2371
#55 0x00007f43f16b77be in QQuickMouseArea::~QQuickMouseArea() (this=0x7f43be8dca80) at items/qquickmousearea.cpp:451
#56 __base_dtor  () at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#57 __deleting_dtor  (this=0x7f43be8dca80) at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#58 0x00007f43f01ddfec in qDeleteInEventHandler(QObject*) () at kernel/qobject.cpp:4599
#59 QObject::event(QEvent*) (this=this@entry=0x7f43be8dca80, e=e@entry=0x7f43e5ac2f40) at kernel/qobject.cpp:1238
#60 0x00007f43f16acebb in QQuickItem::event(QEvent*) (this=0x7f43be8dca80, ev=0x7f43e5ac2f40) at items/qquickitem.cpp:7927
#61 0x00007f43f0b3c796 in QApplicationPrivate::notify_helper(QObject*, QEvent*) [clone .localalias.20] () from /usr/lib64/libQt5Widgets.so.5
#62 0x00007f43f0b3dd17 in QApplication::notify(QObject*, QEvent*) [clone .localalias.86] () from /usr/lib64/libQt5Widgets.so.5
#63 0x00007f43f01abc05 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x7f43be8dca80, event=0x7f43e5ac2f40) at kernel/qcoreapplication.cpp:1050
#64 0x00007f43f01abe9e in QCoreApplication::sendEvent(QObject*, QEvent*) () at kernel/qcoreapplication.h:234
#65 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x7f43e9a6f180)
    at kernel/qcoreapplication.cpp:1740
#66 0x00007f43f02568e8 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1594
#67 0x00007f43f020fa93 in postEventSourceDispatch (s=s@entry=0x7f43e9af3ea0) at kernel/qeventdispatcher_glib.cpp:276
#68 0x00007f43ee99cdc4 in g_main_dispatch (context=0x7f43e820c0c0) at /var/tmp/portage/dev-libs/glib-2.56.1/work/glib-2.56.1/glib/gmain.c:3177
#69 g_main_context_dispatch (context=0x7f43e820c0c0) at /var/tmp/portage/dev-libs/glib-2.56.1/work/glib-2.56.1/glib/gmain.c:3830
#70 0x00007f43ee9b16a9 in g_main_context_iterate.isra.81.lto_priv.208 (context=0x7f43e820c0c0, block=<optimized out>, dispatch=1)
    at /var/tmp/portage/dev-libs/glib-2.56.1/work/glib-2.56.1/glib/gmain.c:3903
#71 0x00007f43ee9994ac in g_main_context_iteration (context=0x7f43e820c0c0, may_block=1) at /var/tmp/portage/dev-libs/glib-2.56.1/work/glib-2.56.1/glib/gmain.c:3964
#72 0x00007f43f02001bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7f43e9a09160, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#73 0x00007f43e9081551 in processEvents (this=0x7f43e9a09160, flags=...) at qeventdispatcher_glib.cpp:69
#74 0x00007f43f0256e65 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fff180b7df0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#75 0x00007f43f01aeabb in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1338
#76 0x0000000000407815 in main (argc=<optimized out>, argv=<optimized out>)

```

**Comment by davidtgoldblatt** [comment]
This looks a lot like an application bug -- going down the sized deallocation pathways straight from a smart pointer + inherited-from base class destructor usually means that there's a missing virtual destructor somewhere, which can cause an incorrect size to get passed to sdallocx (our sized deallocation function).

Is this easily reproducible? Getting the typeid of the object being destroyed at the crash could be helpful. Linking against the debug version of jemalloc will also help catch some of these sorts of bugs.

Unfortunately, as of the last time I checked, neither valgrind nor ASAN will catch sized-deallocation errors, so these sorts of things can be tricky to debug.

**Comment by justanerd** [comment]
Really easy reproducible. I just type something in the krunner and it crashes.
My system runs with jemalloc globally in LD_PRELOAD. Everything besides some kde/plasma applications is fine. I will compile jemalloc with full debug and try to get some more infomation.

**Comment by justanerd** [comment]
Here is a second backtrace with jemalloc in debug mode.

```
<jemalloc>: /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/src/jemalloc.c:2989: Failed assertion: "usize == isalloc(tsd_tsdn(tsd), ptr)"

Thread 1 "krunner" received signal SIGABRT, Aborted.
0x00007ffff5c314a5 in __libc_signal_restore_set (set=<optimized out>) at ../sysdeps/unix/sysv/linux/nptl-signals.h:80
80      ../sysdeps/unix/sysv/linux/nptl-signals.h: No such file or directory.
(gdb) bt
#0  0x00007ffff5c314a5 in __libc_signal_restore_set (set=<optimized out>) at ../sysdeps/unix/sysv/linux/nptl-signals.h:80
#1  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#2  0x00007ffff5c32d11 in __GI_abort () at abort.c:79
#3  0x00007ffff7d24e3d in sdallocx (ptr=ptr@entry=0x7fffe81a8180, size=size@entry=32, flags=flags@entry=0)
    at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/src/jemalloc.c:2989
#4  0x00007ffff7d9cb7c in operator delete (ptr=ptr@entry=0x7fffe81a8180, size=size@entry=32)
    at /var/tmp/portage/dev-libs/jemalloc-5.0.1/work/jemalloc-5.0.1/src/jemalloc_cpp.cpp:131
#5  0x00007ffff799c5a3 in QQmlPrivate::QQmlElement<QQuickText>::~QQmlElement (this=0x7fffe81a8180, __in_chrg=<optimized out>)
    at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#6  0x00007ffff6221acc in QObjectPrivate::deleteChildren (this=this@entry=0x7fffef557480) at kernel/qobject.cpp:1993
#7  0x00007ffff6222dec in QObject::~QObject (this=<optimized out>, __in_chrg=<optimized out>) at kernel/qobject.cpp:1023
#8  0x00007ffff79785f4 in QQuickItem::~QQuickItem (this=0x7fffe819dac0, __in_chrg=<optimized out>) at items/qquickitem.cpp:2371
#9  0x00007ffff7a0f08a in QQuickMouseArea::~QQuickMouseArea (this=<optimized out>, __in_chrg=<optimized out>) at items/qquickmousearea.cpp:451
#10 0x00007ffff799bc58 in QQmlPrivate::QQmlElement<QQuickMouseArea>::~QQmlElement (this=0x7fffe819dac0, __in_chrg=<optimized out>)
    at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#11 QQmlPrivate::QQmlElement<QQuickMouseArea>::~QQmlElement (this=0x7fffe819dac0, __in_chrg=<optimized out>) at ../../include/QtQml/../../src/qml/qml/qqmlprivate.h:104
#12 0x00007ffff621ab84 in qDeleteInEventHandler (o=o@entry=0x7fffe819dac0) at kernel/qobject.cpp:4599
#13 0x00007ffff621c85b in QObject::event (this=this@entry=0x7fffe819dac0, e=e@entry=0x7fffebc3e520) at kernel/qobject.cpp:1238
#14 0x00007ffff7976107 in QQuickItem::event (this=0x7fffe819dac0, ev=0x7fffebc3e520) at items/qquickitem.cpp:7927
#15 0x00007ffff6b9f27d in QApplicationPrivate::notify_helper (this=this@entry=0x7fffef58a000, receiver=receiver@entry=0x7fffe819dac0, e=e@entry=0x7fffebc3e520)
    at kernel/qapplication.cpp:3732
#16 0x00007ffff6ba65db in QApplication::notify (this=0x7fffffffc340, receiver=0x7fffe819dac0, e=0x7fffebc3e520) at kernel/qapplication.cpp:3104
#17 0x00007ffff61ebcd2 in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x7fffe819dac0, event=event@entry=0x7fffebc3e520) at kernel/qcoreapplication.cpp:1050
#18 0x00007ffff61f1da3 in QCoreApplication::sendEvent (event=0x7fffebc3e520, receiver=0x7fffe819dac0) at kernel/qcoreapplication.h:234
#19 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x7fffef380180) at kernel/qcoreapplication.cpp:1740
#20 0x00007ffff61f23fa in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1594
#21 0x00007ffff6245f18 in postEventSourceDispatch (s=s@entry=0x7fffefa7c6c0) at kernel/qeventdispatcher_glib.cpp:276
#22 0x00007ffff4919dc4 in g_main_dispatch (context=0x7fffee2080c0) at /var/tmp/portage/dev-libs/glib-2.56.1/work/glib-2.56.1/glib/gmain.c:3177
#23 g_main_context_dispatch (context=0x7fffee2080c0) at /var/tmp/portage/dev-libs/glib-2.56.1/work/glib-2.56.1/glib/gmain.c:3830
#24 0x00007ffff492e6a9 in g_main_context_iterate.isra.81.lto_priv.208 (context=0x7fffee2080c0, block=<optimized out>, dispatch=1)
    at /var/tmp/portage/dev-libs/glib-2.56.1/work/glib-2.56.1/glib/gmain.c:3903
#25 0x00007ffff49164ac in g_main_context_iteration (context=0x7fffee2080c0, may_block=may_block@entry=1)
    at /var/tmp/portage/dev-libs/glib-2.56.1/work/glib-2.56.1/glib/gmain.c:3964
#26 0x00007ffff624592e in QEventDispatcherGlib::processEvents (this=0x7fffefa00220, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#27 0x00007fffeeff5375 in QPAEventDispatcherGlib::processEvents (this=0x7fffefa00220, flags=...) at qeventdispatcher_glib.cpp:69
#28 0x00007ffff61e9cbd in QEventLoop::processEvents (this=this@entry=0x7fffffffc260, flags=..., flags@entry=...) at kernel/qeventloop.cpp:134
#29 0x00007ffff61ea108 in QEventLoop::exec (this=this@entry=0x7fffffffc260, flags=flags@entry=...) at kernel/qeventloop.cpp:212
#30 0x00007ffff61f3d08 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1338
#31 0x00007ffff656b638 in QGuiApplication::exec () at kernel/qguiapplication.cpp:1687
#32 0x00007ffff6b9f15d in QApplication::exec () at kernel/qapplication.cpp:2917
#33 0x0000000000407815 in main (argc=<optimized out>, argv=<optimized out>)
    at /var/tmp/portage/kde-plasma/plasma-workspace-5.12.4-r1/work/plasma-workspace-5.12.4/krunner/main.cpp:92

```

**Comment by davidtgoldblatt** [comment]
Yeah, this seems like a bug in the application (or Qt).

The assertion is saying that someone is passing jemalloc a pointer that claims to be to a 32-byte allocation, which is in fact did not come from a 32-byte allocation. This usually comes from missing virtual destructors, but it's hard to say for sure. Probably best would be to fix it upstream, but in the short-term it should be possible to tell your compiler not to emit sized-deallocation calls.

**Comment by davidtgoldblatt** [comment]
(Closing for now since that stack trace looks pretty compelling, but feel free to reopen if something starts pointing to a bug in jemalloc).
