### ISSUE TITLE
witness_assert_lockless coredump when malloc is interrupted by a signal

### ISSUE THREAD

**Issue by zengxiaobai** [jemalloc/jemalloc#1224]
I have a core dump as follow for times in jemalloc 5.0.1 when  i kill a signal for reconfiguring to processes.
It seems coredump is occured  when malloc function is interrupted by a signal handler which will call free or malloc again.
```
#0  0x00007f705526d1f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install squid-1.1-0.0.el7.centos.x86_64
(gdb) bt
#0  0x00007f705526d1f7 in raise () from /lib64/libc.so.6
#1  0x00007f705526e8e8 in abort () from /lib64/libc.so.6
#2  0x00007f70566d70c9 in witness_depth_error_impl () from /usr/local/squid/lib/libjemalloc.so.2
#3  0x00007f705665c321 in witness_assert_depth_to_rank () from /usr/local/squid/lib/libjemalloc.so.2
#4  0x00007f705665c346 in witness_assert_depth () from /usr/local/squid/lib/libjemalloc.so.2
#5  0x00007f705665c365 in witness_assert_lockless () from /usr/local/squid/lib/libjemalloc.so.2
#6  0x00007f70566645cf in check_entry_exit_locking () from /usr/local/squid/lib/libjemalloc.so.2
#7  0x00007f7056668b70 in free () from /usr/local/squid/lib/libjemalloc.so.2
#8  0x00007f70552e7c49 in tzset_internal () from /lib64/libc.so.6
#9  0x00007f70552e8613 in __tz_convert () from /lib64/libc.so.6
#10 0x00000000004356a8 in _db_print ()
#11 0x0000000000495ace in polling_reload ()
#12 <signal handler called>
#13 0x00007f705669bdb4 in extent_snad_comp () from /usr/local/squid/lib/libjemalloc.so.2
#14 0x00007f70566a014a in je_extent_heap_remove_first () from /usr/local/squid/lib/libjemalloc.so.2
#15 0x00007f7056675e21 in arena_bin_slabs_nonfull_tryget () from /usr/local/squid/lib/libjemalloc.so.2
#16 0x00007f7056676986 in arena_bin_nonfull_slab_get () from /usr/local/squid/lib/libjemalloc.so.2
#17 0x00007f7056676b05 in arena_bin_malloc_hard () from /usr/local/squid/lib/libjemalloc.so.2
#18 0x00007f7056676de6 in je_arena_tcache_fill_small () from /usr/local/squid/lib/libjemalloc.so.2
#19 0x00007f70566d3a47 in je_tcache_alloc_small_hard () from /usr/local/squid/lib/libjemalloc.so.2
#20 0x00007f705665fd68 in tcache_alloc_small () from /usr/local/squid/lib/libjemalloc.so.2
#21 0x00007f7056660b8d in arena_malloc () from /usr/local/squid/lib/libjemalloc.so.2
#22 0x00007f705666202c in iallocztm () from /usr/local/squid/lib/libjemalloc.so.2
---Type <return> to continue, or q <return> to quit---
#23 0x00007f7056667288 in imalloc_no_sample () from /usr/local/squid/lib/libjemalloc.so.2
#24 0x00007f705666793a in imalloc_body () from /usr/local/squid/lib/libjemalloc.so.2
#25 0x00007f7056667d65 in imalloc () from /usr/local/squid/lib/libjemalloc.so.2
#26 0x00007f7056667f59 in calloc () from /usr/local/squid/lib/libjemalloc.so.2
#27 0x00000000004b02ca in xcalloc ()
#28 0x0000000000480663 in stmemAppend ()
#29 0x0000000000483e46 in storeAppend ()
#30 0x000000000044ebad in httpAppendBody ()
#31 0x00000000004507e3 in httpReadReply ()
#32 0x0000000000434f2e in comm_select ()
#33 0x0000000000409309 in main ()
```

**Comment by davidtgoldblatt** [comment]
This seems like an application bug -- you're calling a function that's not async-signal-safe from an async signal.

Closing for now, feel free to reopen if I'm missing something.
