### ISSUE TITLE
Core in multithreaded application in atomic_store_p() called during [m|c]alloc() (jemalloc v5.1.0)

### ISSUE THREAD

**Issue by ernst-bablick** [jemalloc/jemalloc#1247]
I have a multithreaded application on CentOS7 that used jemalloc v5.1.0. Sometimes this application fails short time after startup in a [c|m]alloc call. Here is one full stack trace for one of the cores:

```
#0  atomic_store_p (mo=atomic_memory_order_release, val=0x117f24cce07241, a=0x3eb0c6f7a0bc4ded)
    at /tools/SRC/jemalloc-5.1.0/include/jemalloc/internal/atomic.h:55
#1  rtree_leaf_elm_write (slab=<optimized out>, szind=3437234560, extent=<optimized out>, elm=0x3eb0c6f7a0bc4ded, rtree=0x6d1620 <je_extents_rtree>, 
    tsdn=<optimized out>) at /tools/SRC/jemalloc-5.1.0/include/jemalloc/internal/rtree.h:301
#2  extent_rtree_write_acquired (tsdn=0x5000, slab=<optimized out>, szind=3437234560, extent=<optimized out>, elm_b=0x3eb0c6f7a0bc4e0d, 
    elm_a=0x3eb0c6f7a0bc4ded) at /tools/SRC/jemalloc-5.1.0/src/extent.c:680
#3  extent_split_impl (tsdn=tsdn@entry=0x7f24ce525740, arena=arena@entry=0x7f24cce00980, r_extent_hooks=<optimized out>, extent=<optimized out>, 
    size_a=size_a@entry=20480, szind_a=szind_a@entry=17, slab_a=<optimized out>, size_b=<optimized out>, szind_b=<optimized out>, slab_b=<optimized out>, 
    growing_retained=true) at /tools/SRC/jemalloc-5.1.0/src/extent.c:2039
#4  0x000000000045c3ea in extent_split_interior (tsdn=tsdn@entry=0x7f24ce525740, arena=arena@entry=0x7f24cce00980, 
    r_extent_hooks=r_extent_hooks@entry=0x7ffd664a45d8, rtree_ctx=rtree_ctx@entry=0x7f24ce525768, extent=extent@entry=0x7ffd664a4278, 
    lead=lead@entry=0x7ffd664a4280, trail=0x7ffd664a4288, to_leak=0x7ffd664a4290, to_salvage=0x7ffd664a4298, size=20480, pad=0, alignment=4096, slab=true, 
    szind=17, growing_retained=true, new_addr=0x565245535f59524f) at /tools/SRC/jemalloc-5.1.0/src/extent.c:972
#5  0x000000000045ee5e in extent_recycle_split (growing_retained=true, extent=<optimized out>, szind=17, slab=true, alignment=4096, pad=0, size=20480, 
    new_addr=0x565245535f59524f, extents=0x7f24cce033b8, rtree_ctx=0x7f24ce525768, r_extent_hooks=0x7ffd664a45d8, arena=0x7f24cce00980, tsdn=0x7f24cce033b8)
    at /tools/SRC/jemalloc-5.1.0/src/extent.c:1021
#6  extent_recycle (tsdn=tsdn@entry=0x7f24ce525740, arena=arena@entry=0x7f24cce00980, r_extent_hooks=r_extent_hooks@entry=0x7ffd664a45d8, 
    extents=extents@entry=0x7f24cce033b8, new_addr=new_addr@entry=0x0, size=size@entry=20480, pad=0, alignment=4096, slab=true, szind=17, 
    zero=0x7ffd664a45d6, commit=0x7ffd664a45d7, growing_retained=true) at /tools/SRC/jemalloc-5.1.0/src/extent.c:1081
#7  0x0000000000460cdc in extent_alloc_retained (commit=0x7ffd664a45d7, zero=0x7ffd664a45d6, szind=17, slab=true, alignment=4096, pad=0, size=20480, 
    new_addr=0x0, r_extent_hooks=0x7ffd664a45d8, arena=0x7f24cce00980, tsdn=0x7f24ce525740) at /tools/SRC/jemalloc-5.1.0/src/extent.c:1398
#8  je_extent_alloc_wrapper (tsdn=tsdn@entry=0x7f24ce525740, arena=arena@entry=0x7f24cce00980, r_extent_hooks=r_extent_hooks@entry=0x7ffd664a45d8, 
    new_addr=new_addr@entry=0x0, size=20480, pad=pad@entry=0, alignment=4096, slab=true, szind=17, zero=0x7ffd664a45d6, commit=0x7ffd664a45d7)
    at /tools/SRC/jemalloc-5.1.0/src/extent.c:1466
#9  0x000000000042ac39 in arena_slab_alloc_hard (bin_info=0x4a68e8 <je_bin_infos+680>, szind=17, r_extent_hooks=0x7ffd664a45d8, arena=0x7f24cce00980, 
    tsdn=0x7f24ce525740) at /tools/SRC/jemalloc-5.1.0/src/arena.c:1103
#10 arena_slab_alloc (bin_info=<optimized out>, binind=17, arena=<optimized out>, tsdn=<optimized out>) at /tools/SRC/jemalloc-5.1.0/src/arena.c:1133
#11 arena_bin_nonfull_slab_get (binind=17, bin=<optimized out>, arena=<optimized out>, tsdn=<optimized out>) at /tools/SRC/jemalloc-5.1.0/src/arena.c:1169
#12 arena_bin_malloc_hard (binind=<optimized out>, bin=<optimized out>, arena=<optimized out>, tsdn=<optimized out>)
    at /tools/SRC/jemalloc-5.1.0/src/arena.c:1205
#13 je_arena_tcache_fill_small (tsdn=tsdn@entry=0x7f24ce525740, arena=arena@entry=0x7f24cce00980, tcache=tcache@entry=0x7f24ce525900, 
    tbin=tbin@entry=0x7f24ce525aa8, binind=17, prof_accumbytes=<optimized out>) at /tools/SRC/jemalloc-5.1.0/src/arena.c:1270
#14 0x000000000049812e in je_tcache_alloc_small_hard (tsdn=tsdn@entry=0x7f24ce525740, arena=arena@entry=0x7f24cce00980, tcache=tcache@entry=0x7f24ce525900, 
    tbin=tbin@entry=0x7f24ce525aa8, binind=<optimized out>, tcache_success=tcache_success@entry=0x7ffd664a4670) at /tools/SRC/jemalloc-5.1.0/src/tcache.c:93
#15 0x000000000041cfce in tcache_alloc_small (slow_path=false, zero=true, binind=17, size=<optimized out>, tcache=0x7f24ce525900, arena=<optimized out>, 
    tsd=<optimized out>) at /tools/SRC/jemalloc-5.1.0/include/jemalloc/internal/tcache_inlines.h:60
#16 arena_malloc (slow_path=false, tcache=0x7f24ce525900, zero=true, ind=17, size=<optimized out>, arena=0x0, tsdn=<optimized out>)
    at /tools/SRC/jemalloc-5.1.0/include/jemalloc/internal/arena_inlines_b.h:94
#17 iallocztm (slow_path=false, arena=0x0, is_internal=false, tcache=0x7f24ce525900, zero=true, ind=17, size=<optimized out>, tsdn=<optimized out>)
    at /tools/SRC/jemalloc-5.1.0/include/jemalloc/internal/jemalloc_internal_inlines_c.h:53
#18 imalloc_no_sample (ind=17, usize=640, size=<optimized out>, tsd=0x7f24ce525740, dopts=<synthetic pointer>, sopts=<synthetic pointer>)
    at /tools/SRC/jemalloc-5.1.0/src/jemalloc.c:1709
#19 imalloc_body (tsd=0x7f24ce525740, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at /tools/SRC/jemalloc-5.1.0/src/jemalloc.c:1905
#20 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at /tools/SRC/jemalloc-5.1.0/src/jemalloc.c:2005
#21 calloc (num=num@entry=520, size=size@entry=1) at /tools/SRC/jemalloc-5.1.0/src/jemalloc.c:2138
#22 0x00007f24cd7158ff in uidgid_state_get_last_username () at ../libs/uti/sge_uidgid.c:2016
#23 0x00007f24cd717220 in sge_uid2user (uid=2003, dst=dst@entry=0x7ffd664a5830 "", sz=sz@entry=128, pdstr_err=pdstr_err@entry=0x7ffd664a5810)
    at ../libs/uti/sge_uidgid.c:795
#24 0x00007f24cd5a2869 in sge_setup2 (context_ref=context_ref@entry=0x7ffd664a61c0, progid=progid@entry=28, thread_id=thread_id@entry=0, 
    alpp=alpp@entry=0x7ffd664a61c8, is_qmaster_intern_client=is_qmaster_intern_client@entry=false) at ../libs/gdi/sge_gdi_ctx.c:2205
#25 0x00007f24cd5a2f4c in sge_gdi2_setup (context_ref=context_ref@entry=0x7ffd664a61c0, progid=progid@entry=28, thread_id=thread_id@entry=0, 
    alpp=alpp@entry=0x7ffd664a61c8) at ../libs/gdi/sge_gdi_ctx.c:2317
#26 0x0000000000403dd7 in main (argc=<optimized out>, argv=<optimized out>) at ../libs/japi/test_drmaa.c:687
```

Parasoft's Insure (memory debugger) has been used to check for memory corruptions. That tool has not detected any issues.

The core does not happen with with jemalloc v5.0.1

**Comment by interwq** [comment]
“szind=3437234560” this still points to memory corruption. I’d suggest trying sanitizers like ASAN first. Then if necessary the debug built of jemalloc (--enable-debug).
