### ISSUE TITLE
jemalloc attempts to mmap memory twice

### ISSUE THREAD

**Issue by trasz** [jemalloc/jemalloc#1260]
I've been working on making jemalloc use the facilities provided by FreeBSD's mmap(2) (#1251), and discovered a curious pattern which looks like a bug: jemalloc often does something like this:

```
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34391683072 (0x801e77000)
mmap(0x801e77000,65536,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34391945216 (0x801eb7000)
munmap(0x801eb7000,65536)                       = 0 (0x0)
```

Look at the first two mmap calls: the first returns 0x801e77000; the next one attempts to create a shorter mapping with explicit address set to... 0x801e77000, the same pointer it just got from the previous call to mmap(2).  Is that intentional?

This is the jemalloc bundled with FreeBSB 12, which seems to be 5.1.0.

**Comment by davidtgoldblatt** [comment]
Huh, that's screwy. One thought I have is that, in realloc'ing, we'll sometimes try to expand a range in place by mmaping directly after a region, even if we could (by being more careful about metadata checking) tell that some arena has already reserved that memory. If the kernel tries to lay out virtual address space consecutively, it could result in a series of calls that look like that. Does that seem plausible given the program activity?

Is it an easy repro?

**Comment by trasz** [comment]
Hm.  Thing is, those occur always in the same specific pattern: it's always an mmap without the address hint, followed by an mmap with address equal to the one returned by the previous one, and a shorter length.  Here's the longer version; it's patched, so you'll see failed mmaps instead of the usual mmaps and munmaps.

```
mmap(0x0,28672,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34379919360 (0x80133f000)                                                                                                   
mmap(0x0,28672,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34379948032 (0x801346000)                                                                                                   
mmap(0x0,28672,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34379976704 (0x80134d000)
mmap(0x0,28672,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34380005376 (0x801354000)                                                                                                   
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34380034048 (0x80135b000)                                                                                                                  
mmap(0x80121d000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) ERR#12 'Cannot allocate memory'
mmap(0x0,24576,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34380296192 (0x80139b000)                                                                                                   
mmap(0x8013a1000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380320768 (0x8013a1000)                                                                                         
mmap(0x8013a2000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380324864 (0x8013a2000)
mmap(0x8013a3000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380328960 (0x8013a3000)
mmap(0x8013a4000,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380333056 (0x8013a4000)                                                                                         
mmap(0x8013a6000,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380341248 (0x8013a6000)                                                                                         
mmap(0x8013a8000,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380349440 (0x8013a8000)
mmap(0x8013aa000,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380357632 (0x8013aa000)
mmap(0x8013ac000,16384,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380365824 (0x8013ac000)                                                                                        
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34380382208 (0x8013b0000)                                                                                                                  
mmap(0x8013b0000,16384,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) ERR#12 'Cannot allocate memory'
mmap(0x0,102400,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34380644352 (0x8013f0000)
mmap(0x801409000,16384,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380746752 (0x801409000)
mmap(0x80140d000,16384,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380763136 (0x80140d000)
mmap(0x801411000,32768,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34380779520 (0x801411000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34380812288 (0x801419000)
mmap(0x801419000,32768,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) ERR#12 'Cannot allocate memory'
mmap(0x0,200704,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34381074432 (0x801459000)
mmap(0x80148a000,32768,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34381275136 (0x80148a000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34381307904 (0x801492000)
mmap(0x801492000,32768,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) ERR#12 'Cannot allocate memory'
mmap(0x0,266240,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34381570048 (0x8014d2000)
mmap(0x801513000,65536,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) = 34381836288 (0x801513000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34381901824 (0x801523000)
mmap(0x801523000,65536,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) ERR#12 'Cannot allocate memory'                                                                                     mmap(0x0,397312,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34382163968 (0x801563000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34382561280 (0x8015c4000)
mmap(0x8015c4000,65536,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) ERR#12 'Cannot allocate memory'
mmap(0x0,462848,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34382823424 (0x801604000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34383286272 (0x801675000)
mmap(0x801675000,65536,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) ERR#12 'Cannot allocate memory'
mmap(0x0,528384,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34383548416 (0x8016b5000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34384076800 (0x801736000)
mmap(0x801736000,131072,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) ERR#12 'Cannot allocate memory'
mmap(0x0,659456,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34384338944 (0x801776000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34384998400 (0x801817000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34385260544 (0x801857000)
mmap(0x801817000,131072,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) ERR#12 'Cannot allocate memory'
mmap(0x0,790528,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34385522688 (0x801897000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34386313216 (0x801958000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34386575360 (0x801998000)
mmap(0x801958000,131072,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON|MAP_EXCL,-1,0x0) ERR#12 'Cannot allocate memory'
mmap(0x0,921600,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34386837504 (0x8019d8000)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34387759104 (0x801ab9000)
```

As for reproducing: it's pretty easy; FreeBSD 12.0, python36-3.6.5 installed from package, running this:

`$ truss python3 meh.py`

The meh.py contains:
```
#!/usr/bin/env python3

[i for i in range(100000)]
```

**Comment by trasz** [comment]
Ping?  Anything I can try to help debugging it?  Thanks!

**Comment by davidtgoldblatt** [comment]
Sorry, I haven't been able to dig into this yet. One thing that might help is the stack trace at the time of the first doomed mmap; that would at least tell us which operation is causing the issue (and maybe we'll get lucky).

**Comment by trasz** [comment]
Ok, it goes like this:
```
(gdb) bt
#0  __je_pages_map (addr=0x801230000, size=4096, alignment=4096, commit=0x7fffffffdd5e) at jemalloc_pages.c:207
#1  0x000000080069e7fd in __je_extent_alloc_mmap (new_addr=0x801230000, size=4096, alignment=64, zero=0x7fffffffdd5f, commit=0x7fffffffdd5e) at jemalloc_extent_mmap.c:26
#2  0x00000008006b5d5a in extent_alloc_core (tsdn=0x80022f090, arena=0x800a009c0, new_addr=0x801230000, size=4096, alignment=64, zero=0x7fffffffdd5f, commit=0x7fffffffdd5e, dss_prec=dss_prec_disabled)
    at jemalloc_extent.c:1154
#3  0x00000008006b5793 in extent_alloc_default_impl (tsdn=0x80022f090, arena=0x800a009c0, new_addr=0x801230000, size=4096, alignment=64, zero=0x7fffffffdd5f, commit=0x7fffffffdd5e) at jemalloc_extent.c:1172
#4  0x00000008006adc10 in extent_alloc_wrapper_hard (tsdn=0x80022f090, arena=0x800a009c0, r_extent_hooks=0x7fffffffdd68, new_addr=0x801230000, size=4096, pad=0, alignment=64, slab=false, szind=232, 
    zero=0x7fffffffdd5f, commit=0x7fffffffdd5e) at jemalloc_extent.c:1432
#5  0x00000008006ad84a in __je_extent_alloc_wrapper (tsdn=0x80022f090, arena=0x800a009c0, r_extent_hooks=0x7fffffffdd68, new_addr=0x801230000, size=4096, pad=0, alignment=64, slab=false, szind=232, 
    zero=0x7fffffffdd5f, commit=0x7fffffffdd5e) at jemalloc_extent.c:1480
#6  0x0000000800699cff in large_ralloc_no_move_expand (tsdn=0x80022f090, extent=0x800a0a180, usize=20480, zero=false) at jemalloc_large.c:167
#7  0x0000000800699930 in __je_large_ralloc_no_move (tsdn=0x80022f090, extent=0x800a0a180, usize_min=20480, usize_max=20480, zero=false) at jemalloc_large.c:232
#8  0x000000080069a38f in __je_large_ralloc (tsdn=0x80022f090, arena=0x0, extent=0x800a0a180, usize=20480, alignment=0, zero=false, tcache=0x80022f250) at jemalloc_large.c:285
#9  0x00000008006d5c46 in __je_arena_ralloc (tsdn=0x80022f090, arena=0x0, ptr=0x80122b700, oldsize=16384, size=16496, alignment=0, zero=false, tcache=0x80022f250) at jemalloc_arena.c:1649
#10 0x00000008006e1fe8 in iralloct (tsdn=0x80022f090, ptr=0x80122b700, oldsize=<optimized out>, size=16496, alignment=0, zero=<optimized out>, tcache=0x80022f250, arena=0x0)
    at /usr/home/trasz/svn-ssh/head/contrib/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h:190
#11 0x00000008006e05f5 in iralloc (alignment=0, zero=false, tsd=<optimized out>, ptr=<optimized out>, oldsize=<optimized out>, size=<optimized out>)
    at /usr/home/trasz/svn-ssh/head/contrib/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h:197
#12 __realloc (ptr=0x80122b700, size=16496) at jemalloc_jemalloc.c:2342
#13 0x000000080038dac6 in PyList_Append () from /usr/local/lib/libpython3.6m.so.1.0
#14 0x0000000800424d5e in _PyEval_EvalFrameDefault () from /usr/local/lib/libpython3.6m.so.1.0
#15 0x000000080042ccf0 in ?? () from /usr/local/lib/libpython3.6m.so.1.0
#16 0x000000080042bb54 in ?? () from /usr/local/lib/libpython3.6m.so.1.0
#17 0x00000008004291e4 in _PyEval_EvalFrameDefault () from /usr/local/lib/libpython3.6m.so.1.0
#18 0x000000080042c463 in ?? () from /usr/local/lib/libpython3.6m.so.1.0
#19 0x0000000800422fd3 in PyEval_EvalCode () from /usr/local/lib/libpython3.6m.so.1.0
#20 0x00000008004561de in PyRun_FileExFlags () from /usr/local/lib/libpython3.6m.so.1.0
#21 0x00000008004557e8 in PyRun_SimpleFileExFlags () from /usr/local/lib/libpython3.6m.so.1.0
#22 0x00000008004707e7 in Py_Main () from /usr/local/lib/libpython3.6m.so.1.0
#23 0x00000000002013bb in main ()
```

**Comment by trasz** [comment]
Hello.  So, any idea what might be going on here?  Were you able to check if the same happens on Linux?

**Comment by davidtgoldblatt** [comment]
Tossing to @interwq, since I don't think I'll be able to take a look.

**Comment by trasz** [comment]
Okay, so this one _might_ be a false positive.  Basically, it seems to be jemalloc (doing the mmaps with MAP_EXCL) tripping over the Python's internal allocator (the 262144 without MAP_EXCL nor MAP_ALIGNED).  I'll take another look later and if that's true then we can close it.

**Comment by trasz** [comment]
Yup, it's Python's fault.  Sorry for the noise.
