### ISSUE TITLE
failed tests under CYGWIN

### ISSUE THREAD

**Issue by thefallentree** [jemalloc/jemalloc#1414]
Hi there,

I'm trying to get CYGWIN compilation going (again) with release 5.1.0 , here what I found working and not working.

Working:
1. no <sys/syscall.h> under CYGWIN, so that need fixing.
2. remove override of DUMPSYM in configure.ac (search for cygwin) , I can successful compile.

Not working:
1. TSD unit test has issue. 
```
test_tsd_sub_thread:test/unit/tsd.c:83: Failed assertion: (data_cleanup_count) >= (3) --> 0x1 < 0x3: Cleanup function should have executed multiple times.
```
2. integration test get stackdump
```
=== test/integration/cpp/basic ===
test/test.sh: line 34:  6732 Segmentation fault      (core dumped) $JEMALLOC_TEST_PREFIX ${t}.exe /home/aunyx/src/jemalloc-5.1.0/ /home/aunyx/src/jemalloc-5.1.0/
Test harness error: test/integration/cpp/basic w/ MALLOC_CONF=""
Use prefix to debug, e.g. JEMALLOC_TEST_PREFIX="gdb --args" sh test/test.sh test/integration/cpp/basic
make: *** [Makefile:496: check_integration] Error 1

aunyx@wks-home ~/src/jemalloc-5.1.0
$ JEMALLOC_TEST_PREFIX="gdb --args" sh test/test.sh test/integration/cpp/basic
=== test/integration/cpp/basic ===
GNU gdb (GDB) (Cygwin 8.0.1-1) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-cygwin".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from test/integration/cpp/basic.exe...done.
(gdb) run
Starting program: /home/aunyx/src/jemalloc-5.1.0/test/integration/cpp/basic.exe /home/aunyx/src/jemalloc-5.1.0/ /home/aunyx/src/jemalloc-5.1.0/
[New Thread 15468.0x440]
[New Thread 15468.0x4978]
[New Thread 15468.0x349c]
[New Thread 15468.0xe48]
[New Thread 15468.0x4170]

Thread 1 "basic" received signal SIGSEGV, Segmentation fault.
rtree_szind_slab_read (r_slab=<synthetic pointer>, r_szind=<synthetic pointer>, dependent=true, key=25770182352, rtree_ctx=<optimized out>, rtree=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/rtree.h:464
464             uintptr_t bits = rtree_leaf_elm_bits_read(tsdn, rtree, elm, dependent);
(gdb) bt
#0  rtree_szind_slab_read (r_slab=<synthetic pointer>, r_szind=<synthetic pointer>, dependent=true, key=25770182352, rtree_ctx=<optimized out>, rtree=<optimized out>, tsdn=<optimized out>)
    at include/jemalloc/internal/rtree.h:464
#1  ifree (slow_path=false, tcache=<optimized out>, ptr=0x60005c6d0, tsd=0x6ffffd10008) at src/jemalloc.c:2206
#2  je_free (ptr=0x60005c6d0) at src/jemalloc.c:2393
#3  0x00000001004010ae in test_basic () at test/integration/cpp/basic.cpp:7
#4  0x0000000100403dfc in p_test_impl (do_malloc_init=do_malloc_init@entry=true, do_reentrant=do_reentrant@entry=true, t=0x100401080 <test_basic()>, ap=ap@entry=0xffffcb88 "") at test/src/test.c:135
#5  0x00000001004042df in p_test (t=<optimized out>) at test/src/test.c:177
#6  0x0000000180049e16 in _cygwin_exit_return () at /usr/src/debug/cygwin-2.11.2-1/winsup/cygwin/dcrt0.cc:1018
#7  0x0000000180047973 in _cygtls::call2 (this=0xffffce00, func=0x180048df0 <dll_crt0_1(void*)>, arg=0x0, buf=buf@entry=0xffffcdf0) at /usr/src/debug/cygwin-2.11.2-1/winsup/cygwin/cygtls.cc:40
#8  0x0000000180047a24 in _cygtls::call (func=<optimized out>, arg=<optimized out>) at /usr/src/debug/cygwin-2.11.2-1/winsup/cygwin/cygtls.cc:27
#9  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) c
Continuing.
      1 [main] basic 15468 cygwin_exception::open_stackdumpfile: Dumping stack trace to basic.exe.stackdump
[Thread 15468.0xe48 exited with code 35584]
[Thread 15468.0x349c exited with code 35584]
[Thread 15468.0x4978 exited with code 35584]
[Inferior 1 (process 15468) exited with code 0105400]
(gdb)

Exception: STATUS_ACCESS_VIOLATION at rip=0049FB57377
rax=0000000000000028 rbx=000006FFFFD10068 rcx=0000000000000000
rdx=0000000000000070 rsi=000006FFFFD10030 rdi=000006FFFFD10008
r8 =000006FFFFD10090 r9 =0000000000000001 r10=0000000000000000
r11=0000000600000000 r12=000006FFFFD101C8 r13=0000000600000000
r14=0000000000000000 r15=00000000FFFFCB88
rbp=000000060005C6D0 rsp=00000000FFFFB1C0
program=E:\cygwin\home\aunyx\src\jemalloc-5.1.0\test\integration\cpp\basic.exe, pid 15468, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0060005C6D0  0049FB57377 (0018014BC59, 6FFFFE00D80, 00000000001, 00100401080)
0049FBCD1D0  001004010AE (00000000000, 00180048070, 001801D7F01, 00100401070)
0049FBCD1D0  00100403DFC (00100405039, 000FFFFCCD0, 0018022DE30, 000FFFFCC76)
000FFFFCCD0  001004042DF (00000000000, 0060001803F, 00000000000, 30001000000FF00)
000FFFFCCD0  00180049E16 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180047973 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180047A24 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
```

**Comment by thefallentree** [comment]
Note: I didn't define _WIN32  here,  force define _WIN32 has its own set of problems which I think worth an separate tracking.

**Comment by thefallentree** [comment]
any one have some pointers on what is going on?
