### ISSUE TITLE
newly introduced mallctl tests fails on armv7

### ISSUE THREAD

**Issue by sharkcz** [jemalloc/jemalloc#1911]
The newly introduced mallctl test (commit ) fails on armv7 arch.
````
=== test/stress/mallctl ===
10000000 iterations, mallctl_short=3735505us, mallctlbymib_short=1092147us, ratio=1:3.420
test_mallctl_vs_mallctlbymib_short (non-reentrant): pass
test/test.sh: řádek 34: 24476 Aborted                 (core dumped [obraz paměti uložen]) $JEMALLOC_TEST_PREFIX ${t} /home/sharkcz/projects/jemalloc/ /home/sharkcz/projects/jemalloc/
Test harness error: test/stress/mallctl w/ MALLOC_CONF=""
Use prefix to debug, e.g. JEMALLOC_TEST_PREFIX="gdb --args" sh test/test.sh test/stress/mallctl
make: *** [Makefile:620: stress] Chyba 1
````

When re-run under gdb I see the following backtrace
````
(gdb) run
Starting program: /home/sharkcz/projects/jemalloc/test/stress/mallctl /home/sharkcz/projects/jemalloc/ /home/sharkcz/projects/jemalloc/
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.30-11.fc31.armv7hl
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
10000000 iterations, mallctl_short=3732504us, mallctlbymib_short=1089147us, ratio=1:3.427
test_mallctl_vs_mallctlbymib_short (non-reentrant): pass

Program received signal SIGABRT, Aborted.
0xb6b9123c in raise () from /lib/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install libgcc-9.3.1-2.fc31.armv7hl libstdc++-9.3.1-2.fc31.armv7hl
(gdb) where
#0  0xb6b9123c in raise () from /lib/libc.so.6
#1  0xb6b7a860 in abort () from /lib/libc.so.6
#2  0x00011400 in mallctlbymib_long () at test/stress/mallctl.c:50
#3  0x0001192c in time_func (nwarmup=<optimized out>, niter=<optimized out>, func=0x11360 <mallctlbymib_long>, timer=0xbeffedf0) at test/include/test/bench.h:7
#4  compare_funcs (nwarmup=10000000, niter=10000000, func_b=0x11360 <mallctlbymib_long>, name_b=0x86f68 "mallctlbymib_long", func_a=0x114a8 <mallctl_long>, name_a=0x86f7c "mallctl_long")
    at test/include/test/bench.h:30
#5  test_mallctl_vs_mallctlbymib_long () at test/stress/mallctl.c:64
#6  0x00086114 in p_test_impl (do_reentrant=false, ap=..., t=<optimized out>, do_malloc_init=true) at test/src/test.c:149
#7  p_test_no_reentrancy (t=0x115f0 <test_mallctl_vs_mallctlbymib_short>) at test/src/test.c:207
#8  0xb6b7ad80 in __libc_start_main () from /lib/libc.so.6
#9  0x0001129c in _start () at test/stress/mallctl.c:71
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
````

**Comment by sharkcz** [comment]
there is no such problem on any other arch in our CI

**Comment by davidtgoldblatt** [comment]
Thanks! I believe the fix is in https://github.com/jemalloc/jemalloc/pull/1913 .
