### ISSUE TITLE
Seeing lock contention in jemalloc on 64/128 core server

### ISSUE THREAD

**Issue by bryancall** [jemalloc/jemalloc#1978]
We just installed some new AMD 64 core / 128 threaded servers and I am running a benchmark to test our server.  I am seeing lock contention which looks like it is in jemalloc.  We are running jemalloc 5.2.1.  I am happy to run additional tests or try out new code on these servers.

From perf report:
```
#   Overhead  Shared Object         Symbol
# ..........  ....................  ..................................................
#
      33.52%  [kernel.vmlinux]      [k] native_queued_spin_lock_slowpath
       2.22%  libjemalloc.so.2      [.] je_malloc_mutex_lock_slow
       1.99%  libpthread-2.17.so    [.] pthread_mutex_trylock
```

Backtrace from pstack:
```
Thread 133 (Thread 0x2b1b3428e700 (LWP 91072)):
#0  0x00002b1b304f954d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00002b1b304f4e9b in _L_lock_883 () from /lib64/libpthread.so.0
#2  0x00002b1b304f4d68 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00002b1b3007f08f in malloc_mutex_lock_final (mutex=0x2b1b334031a8) at ../../../../_vcs/jemalloc/include/jemalloc/internal/mutex.h:155
#4  je_malloc_mutex_lock_slow (mutex=mutex@entry=0x2b1b334031a8) at ../../../../_vcs/jemalloc/src/mutex.c:85
#5  0x00002b1b30077938 in malloc_mutex_lock (mutex=0x2b1b334031a8, tsdn=0x2b1b3428cea8) at ../../../../_vcs/jemalloc/include/jemalloc/internal/mutex.h:221
#6  extent_recycle_extract (slab=false, growing_retained=false, alignment=4096, pad=4096, size=16384, new_addr=0x0, extents=0x2b1b334031a8, rtree_ctx=0x2b1b3428ced8, r_extent_hooks=0x2b1b34286618, arena=0x2b1b334008c0, tsdn=0x2b1b3428cea8) at ../../../../_vcs/jemalloc/src/extent.c:917
#7  extent_recycle (tsdn=tsdn@entry=0x2b1b3428cea8, arena=arena@entry=0x2b1b334008c0, r_extent_hooks=r_extent_hooks@entry=0x2b1b34286618, extents=extents@entry=0x2b1b334031a8, new_addr=new_addr@entry=0x0, size=size@entry=16384, pad=4096, alignment=4096, slab=false, szind=36, zero=0x2b1b3428667f, commit=0x2b1b34286617, growing_retained=false) at ../../../../_vcs/jemalloc/src/extent.c:1141
#8  0x00002b1b300782f8 in je_extents_alloc (tsdn=tsdn@entry=0x2b1b3428cea8, arena=arena@entry=0x2b1b334008c0, r_extent_hooks=r_extent_hooks@entry=0x2b1b34286618, extents=extents@entry=0x2b1b334031a8, new_addr=new_addr@entry=0x0, size=size@entry=16384, pad=4096, alignment=4096, slab=false, szind=36, zero=0x2b1b3428667f, commit=0x2b1b34286617) at ../../../../_vcs/jemalloc/src/extent.c:545
#9  0x00002b1b3003ff86 in je_arena_extent_alloc_large (tsdn=tsdn@entry=0x2b1b3428cea8, arena=arena@entry=0x2b1b334008c0, usize=usize@entry=16384, alignment=alignment@entry=4096, zero=zero@entry=0x2b1b3428667f) at ../../../../_vcs/jemalloc/src/arena.c:438
#10 0x00002b1b3007b049 in je_large_palloc (tsdn=tsdn@entry=0x2b1b3428cea8, arena=arena@entry=0x2b1b334008c0, usize=16384, alignment=4096, zero=<optimized out>) at ../../../../_vcs/jemalloc/include/jemalloc/internal/arena_inlines_b.h:18
#11 0x00002b1b3004343c in je_arena_palloc (tsdn=tsdn@entry=0x2b1b3428cea8, arena=0x2b1b334008c0, usize=usize@entry=16384, alignment=alignment@entry=4096, zero=<optimized out>, tcache=tcache@entry=0x0) at ../../../../_vcs/jemalloc/src/arena.c:1546
#12 0x00002b1b30035744 in ipallocztm (arena=<optimized out>, is_internal=false, tcache=0x0, zero=<optimized out>, alignment=4096, usize=16384, tsdn=<optimized out>) at ../../../../_vcs/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h:78
#13 ipalloct (arena=<optimized out>, tcache=0x0, zero=<optimized out>, alignment=4096, usize=16384, tsdn=<optimized out>) at ../../../../_vcs/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h:89
#14 imalloc_no_sample (ind=<optimized out>, usize=16384, size=4096, tsd=<optimized out>, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at ../../../../_vcs/jemalloc/src/jemalloc.c:1945
#15 imalloc_body (tsd=<optimized out>, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at ../../../../_vcs/jemalloc/src/jemalloc.c:2149
#16 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at ../../../../_vcs/jemalloc/src/jemalloc.c:2258
#17 mallocx (size=size@entry=4096, flags=<optimized out>) at ../../../../_vcs/jemalloc/src/jemalloc.c:3137
#18 0x00002b1b2e6cfc98 in jearena::JemallocNodumpAllocator::allocate (this=<optimized out>, f=0x2b1b321cc000) at ../../../../../../_vcs/trafficserver9/src/tscore/JeAllocator.cc:107
```

From a script I wrote to use the output of futex.stp and break inside of the running server to see where the mutexs are:
```
lock: [ET_NET 81][25919] lock 0x2b54f7e031e8 contended 2758556 times, 189 avg us - total wait: 521367084
        #0  0x00002b54f4eceff3 in pthread_mutex_trylock () from /lib64/libpthread.so.0
        #1  0x00002b54f4a514cd in malloc_mutex_trylock_final (mutex=0x2b54f7e031a8) at ../../../../_vcs/jemalloc/include/jemalloc/internal/mutex.h:220
        #2  malloc_mutex_lock (mutex=0x2b54f7e031a8, tsdn=0x2b551b7feea8) at ../../../../_vcs/jemalloc/include/jemalloc/internal/mutex.h:220
        #3  extent_recycle_extract (slab=false, growing_retained=false, alignment=4096, pad=4096, size=32768, new_addr=0x0, extents=0x2b54f7e031a8, rtree_ctx=0x2b551b7feed8, r_extent_hooks=0x2b551b7f9cb8, arena=0x2b54f7e008c0, tsdn=0x2b
551b7feea8) at ../../../../_vcs/jemalloc/src/extent.c:917
        #4  extent_recycle (tsdn=tsdn@entry=0x2b551b7feea8, arena=arena@entry=0x2b54f7e008c0, r_extent_hooks=r_extent_hooks@entry=0x2b551b7f9cb8, extents=extents@entry=0x2b54f7e031a8, new_addr=new_addr@entry=0x0, size=size@entry=32768,
pad=4096, alignment=4096, slab=false, szind=40, zero=0x2b551b7f9d1f, commit=0x2b551b7f9cb7, growing_retained=false) at ../../../../_vcs/jemalloc/src/extent.c:1141
        #5  0x00002b54f4a522f8 in je_extents_alloc (tsdn=tsdn@entry=0x2b551b7feea8, arena=arena@entry=0x2b54f7e008c0, r_extent_hooks=r_extent_hooks@entry=0x2b551b7f9cb8, extents=extents@entry=0x2b54f7e031a8, new_addr=new_addr@entry=0x0,
 size=size@entry=32768, pad=4096, alignment=4096, slab=false, szind=40, zero=0x2b551b7f9d1f, commit=0x2b551b7f9cb7) at ../../../../_vcs/jemalloc/src/extent.c:545
        #6  0x00002b54f4a19f86 in je_arena_extent_alloc_large (tsdn=tsdn@entry=0x2b551b7feea8, arena=arena@entry=0x2b54f7e008c0, usize=usize@entry=32768, alignment=alignment@entry=4096, zero=zero@entry=0x2b551b7f9d1f) at ../../../../_vc
s/jemalloc/src/arena.c:438
        #7  0x00002b54f4a55049 in je_large_palloc (tsdn=tsdn@entry=0x2b551b7feea8, arena=arena@entry=0x2b54f7e008c0, usize=32768, alignment=4096, zero=<optimized out>) at ../../../../_vcs/jemalloc/include/jemalloc/internal/arena_inlines
_b.h:18
        #8  0x00002b54f4a1d43c in je_arena_palloc (tsdn=tsdn@entry=0x2b551b7feea8, arena=0x2b54f7e008c0, usize=usize@entry=32768, alignment=alignment@entry=4096, zero=<optimized out>, tcache=tcache@entry=0x0) at ../../../../_vcs/jemallo
c/src/arena.c:1546
        #9  0x00002b54f4a0f744 in ipallocztm (arena=<optimized out>, is_internal=false, tcache=0x0, zero=<optimized out>, alignment=4096, usize=32768, tsdn=<optimized out>) at ../../../../_vcs/jemalloc/include/jemalloc/internal/jemalloc
_internal_inlines_c.h:78
        #10 ipalloct (arena=<optimized out>, tcache=0x0, zero=<optimized out>, alignment=4096, usize=32768, tsdn=<optimized out>) at ../../../../_vcs/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h:89
        #11 imalloc_no_sample (ind=<optimized out>, usize=32768, size=32768, tsd=<optimized out>, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at ../../../../_vcs/jemalloc/src/jemalloc.c:1945
        #12 imalloc_body (tsd=<optimized out>, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at ../../../../_vcs/jemalloc/src/jemalloc.c:2149
        #13 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at ../../../../_vcs/jemalloc/src/jemalloc.c:2258
        #14 mallocx (size=size@entry=32768, flags=<optimized out>) at ../../../../_vcs/jemalloc/src/jemalloc.c:3137
        #15 0x00002b54f30a9c98 in jearena::JemallocNodumpAllocator::allocate (this=<optimized out>, f=0x2b54f6bde000) at ../../../../../../_vcs/trafficserver9/src/tscore/JeAllocator.cc:107
```

**Comment by davidtgoldblatt** [comment]
From the stack trace, it seems like this call is coming in via a custom arena; am I right in guessing that the whole process is using a single arena for the nodump needs?

The arena is sort of the unit of lock sharding in jemalloc. One possibility would be to create multiple of these no-dump arenas and create thread affinity to them (e.g. if you have 4 arenas you spread requests across, contention should go down by a factor of 4 or so).

**Comment by bryancall** [comment]
@davidtgoldblatt Thank you, I am pretty sure that is the issue.  I am investigating it now.
