### ISSUE TITLE
jemalloc crashes on random places

### ISSUE THREAD

**Issue by xphoenix** [jemalloc/jemalloc#1985]
Version: 5.2.1
Behaviour: crashes with random application stacks
Usage: statically link, ensure that jemalloc is the first in library list
Compiler: gcc-7.3.1, c++17
What have I cheked:
- check ```ld ---verbose``` output and yes, jemalloc is the first in the list
- build application without jemalloc but with address and memory sanitizer and with -fsized-deallocation. Application works fine

When built with jemalloc it randomly crashes causing deadlock in application due to signal handler:
```
#0  atomic_load_p (mo=atomic_memory_order_relaxed, a=<optimized out>) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/include/jemalloc/internal/atomic.h:62
#1  rtree_leaf_elm_bits_read (dependent=true, elm=<optimized out>, rtree=<optimized out>, tsdn=<optimized out>) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/include/jemalloc/internal/rtree.h:162
#2  rtree_szind_slab_read_fast (r_slab=<synthetic pointer>, r_szind=<synthetic pointer>, key=0, rtree_ctx=<optimized out>, rtree=<optimized out>, tsdn=<optimized out>)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/include/jemalloc/internal/rtree.h:474
#3  emap_alloc_ctx_try_lookup_fast (alloc_ctx=<synthetic pointer>, ptr=0x0, emap=<optimized out>, tsd=<optimized out>)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/include/jemalloc/internal/emap.h:194
#4  free_fastpath (size_hint=false, size=0, ptr=ptr@entry=0x0) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/jemalloc.c:2703
#5  free (ptr=ptr@entry=0x0) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/jemalloc.c:2761
#6  0x00007f342d4ba733 in _IO_vfprintf_internal (s=<optimized out>, format=<optimized out>, ap=<optimized out>) at vfprintf.c:2058
#7  0x00007f342d4bfe5b in buffered_vfprintf (s=s@entry=0x7f342d83a1c0 <_IO_2_1_stderr_>, format=format@entry=0x1024a8c " in thread %u:\n", args=args@entry=0x7f3339bf1328) at vfprintf.c:2319
#8  0x00007f342d4ba81e in _IO_vfprintf_internal (s=0x7f342d83a1c0 <_IO_2_1_stderr_>, format=0x1024a8c " in thread %u:\n", ap=ap@entry=0x7f3339bf1328) at vfprintf.c:1289
#9  0x00007f342d4c5407 in __fprintf (stream=stream@entry=0x7f342d83a1c0 <_IO_2_1_stderr_>, format=format@entry=0x1024a8c " in thread %u:\n") at fprintf.c:32
#10 0x00000000007a0aab in print_header (this=0x7f3339bf15e0, thread_id=2271, os=0x7f342d83a1c0 <_IO_2_1_stderr_>) at /usr/src/debug/crow-cluster/third-party/backward-cpp/backward.hpp:1777
#11 backward::Printer::print<backward::StackTrace> (this=this@entry=0x7f3339bf15e0, st=..., os=0x7f342d83a1c0 <_IO_2_1_stderr_>) at /usr/src/debug/crow-cluster/third-party/backward-cpp/backward.hpp:1750
#12 0x00000000007a0ec4 in backward::SignalHandling::sig_handler (info=0x7f3339bf17b0, _ctx=<optimized out>) at /usr/src/debug/crow-cluster/third-party/backward-cpp/backward.hpp:1967
#13 <signal handler called>
#14 atomic_store_p (mo=atomic_memory_order_release, val=0xe8000000000000, a=0x5600) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/include/jemalloc/internal/atomic.h:62
#15 rtree_leaf_elm_write (slab=false, szind=232, edata=0x0, elm=0x5600, rtree=<optimized out>, tsdn=0x7f3339bf4390) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/include/jemalloc/internal/rtree.h:288
#16 emap_rtree_write_acquired (slab=false, szind=232, edata=0x0, elm_b=0x7f2cf8d54140, elm_a=0x5600, emap=<optimized out>, tsdn=0x7f3339bf4390)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/emap.c:142
#17 je_emap_deregister_boundary (tsdn=tsdn@entry=0x7f3339bf4390, emap=<optimized out>, edata=edata@entry=0x7f33c8dcf970) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/emap.c:186
#18 0x00000000009dcdea in extent_deregister_impl (tsdn=tsdn@entry=0x7f3339bf4390, edata=0x7f33c8dcf970, gdump=gdump@entry=true) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/extent.c:357
#19 0x00000000009df72f in extent_deregister (edata=<optimized out>, tsdn=0x7f3339bf4390) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/extent.c:371
#20 extent_recycle_split (growing_retained=<optimized out>, edata=<optimized out>, szind=40, slab=false, alignment=64, pad=4096, size=32768, new_addr=0x0, ecache=0x7f33388031a8, ehooks=0x7f33388000c0, 
    arena=0x7f33388008c0, tsdn=0x7f3339bf4390) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/extent.c:570
#21 extent_recycle (tsdn=tsdn@entry=0x7f3339bf4390, arena=arena@entry=0x7f33388008c0, ehooks=ehooks@entry=0x7f33388000c0, ecache=ecache@entry=0x7f33388031a8, new_addr=new_addr@entry=0x0, size=size@entry=32768, 
    pad=<optimized out>, alignment=<optimized out>, slab=<optimized out>, szind=<optimized out>, zero=<optimized out>, commit=<optimized out>, growing_retained=<optimized out>)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/extent.c:605
#22 0x00000000009df861 in je_ecache_alloc (tsdn=tsdn@entry=0x7f3339bf4390, arena=arena@entry=0x7f33388008c0, ehooks=ehooks@entry=0x7f33388000c0, ecache=ecache@entry=0x7f33388031a8, new_addr=new_addr@entry=0x0, 
    size=size@entry=32768, pad=4096, alignment=64, slab=false, szind=40, zero=0x7f3339bf1f8f) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/extent.c:108
#23 0x00000000009a53b5 in je_arena_extent_alloc_large (tsdn=tsdn@entry=0x7f3339bf4390, arena=arena@entry=0x7f33388008c0, usize=usize@entry=32768, alignment=alignment@entry=64, zero=zero@entry=0x7f3339bf1f8f)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/arena.c:434
#24 0x00000000009e1be2 in je_large_palloc (tsdn=tsdn@entry=0x7f3339bf4390, arena=arena@entry=0x7f33388008c0, usize=32768, alignment=alignment@entry=64, zero=zero@entry=false)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/large.c:48
#25 0x00000000009e207e in je_large_malloc (tsdn=tsdn@entry=0x7f3339bf4390, arena=arena@entry=0x7f33388008c0, usize=<optimized out>, zero=zero@entry=false)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/large.c:18
#26 0x000000000099436c in tcache_alloc_large (slow_path=false, zero=false, binind=<optimized out>, size=32768, tcache=0x7f3339bf45d8, arena=<optimized out>, tsd=<optimized out>)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/include/jemalloc/internal/tcache_inlines.h:108
#27 arena_malloc (slow_path=false, tcache=0x7f3339bf45d8, zero=false, ind=<optimized out>, size=32768, arena=0x0, tsdn=<optimized out>)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/include/jemalloc/internal/arena_inlines_b.h:173
#28 iallocztm (slow_path=false, arena=0x0, is_internal=false, tcache=0x7f3339bf45d8, zero=false, ind=<optimized out>, size=32768, tsdn=<optimized out>)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/include/jemalloc/internal/jemalloc_internal_inlines_c.h:53
#29 imalloc_no_sample (ind=<optimized out>, usize=32768, size=32768, tsd=0x7f3339bf4390, dopts=<synthetic pointer>, sopts=<synthetic pointer>)
    at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/jemalloc.c:2005
#30 imalloc_body (tsd=0x7f3339bf4390, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/jemalloc.c:2196
#31 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/jemalloc.c:2303
#32 je_malloc_default (size=32768) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/jemalloc.c:2334
#33 0x00000000009953a4 in malloc (size=size@entry=32768) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/jemalloc.c:2442
#34 0x0000000000a1b859 in newImpl<false> (size=32768) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/jemalloc_cpp.cpp:92
#35 operator new (size=32768) at /usr/src/debug/crow-cluster/third-party/jemalloc-5.2.1/src/jemalloc_cpp.cpp:139
#36 0x00000000008e0f24 in allocate (this=<optimized out>, __n=<optimized out>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/ext/new_allocator.h:111
#37 allocate (__a=..., __n=<optimized out>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/alloc_traits.h:436
---Type <return> to continue, or q <return> to quit---
#38 _M_allocate (this=<optimized out>, __n=<optimized out>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/stl_vector.h:172
```

Looks like heap corruption, for me at least, but sanitizers are unnable to find anyting. Server built without jemalloc works weeks under load without leaking or any noticable problem with memory :(

**Comment by xphoenix** [comment]
Problem solved, sorry for falsa alarm. It was mistake in puppet, so application was launched with LD_PRELOAD and newer malloc version compiled in :(
