### ISSUE TITLE
Deadlock in __nptl_deallocate_tsd 

### ISSUE THREAD

**Issue by chk-jxcn** [jemalloc/jemalloc#2015]
Jemalloc version is `5.1.0-0-g61efbda7098de6fe64c362d309824864308c36d4`

A thread wait for mutex hold by itself?
```
(gdb) thread 1542
[Switching to thread 1542 (Thread 0x7f3667f03700 (LWP 27169))]
#0  0x00007f378029a734 in __lll_lock_wait () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f378029a734 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f37802961bc in _L_lock_518 () from /lib64/libpthread.so.0
#2  0x00007f378029600b in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007f3781eee119 in malloc_mutex_lock_final (mutex=0x7f3773e06158) at ../include/jemalloc/internal/mutex.h:141
#4  je_malloc_mutex_lock_slow (mutex=mutex@entry=0x7f3773e06158) at ../src/mutex.c:84
#5  0x00007f3781f176da in malloc_mutex_lock (mutex=0x7f3773e06158, tsdn=0x7f3667f01f00) at ../include/jemalloc/internal/mutex.h:205
#6  je_tcache_bin_flush_small (tsd=tsd@entry=0x7f3667f01f00, tcache=tcache@entry=0x7f3667f020c0, tbin=tbin@entry=0x7f3667f02310, binind=binind@entry=24, rem=0) at ../src/tcache.c:173
#7  0x00007f3781f19cc8 in tcache_flush_cache (tcache=0x7f3667f020c0, tsd=0x7f3667f01f00) at ../src/tcache.c:463
#8  tcache_destroy (tsd=0x7f3667f01f00, tcache=0x7f3667f020c0, tsd_tcache=true) at ../src/tcache.c:493
#9  0x00007f3781f1c545 in tsd_do_data_cleanup (tsd=0x7f3667f01f00) at ../src/tsd.c:209
#10 je_tsd_cleanup (arg=0x7f3667f01f00) at ../src/tsd.c:234
#11 0x00007f3780293cf2 in __nptl_deallocate_tsd () from /lib64/libpthread.so.0
#12 0x00007f3780293f48 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f37812108fd in clone () from /lib64/libc.so.6
(gdb) f 3
#3  0x00007f3781eee119 in malloc_mutex_lock_final (mutex=0x7f3773e06158) at ../include/jemalloc/internal/mutex.h:141
141             MALLOC_MUTEX_LOCK(mutex);
(gdb) p *mutex
$12 = {{{prof_data = {tot_wait_time = {ns = 102999815}, max_wait_time = {ns = 68999880}, n_wait_times = 43, n_spin_acquired = 0, max_n_thds = 1, n_waiting_thds = {repr = 15}, n_owner_switches = 312227, prev_owner = 0x7f3667f01f00, n_lock_ops = 578595}, lock = {__data = {__lock = 2, __count = 0, __owner = 27169, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = "\002\000\000\000\000\000\000\000!j", '\000' <repeats 29 times>, __align = 2}}, witness = {name = 0x623a707 <Address 0x623a707 out of bounds>, rank = 68999880, comp = 0x2b, opaque = 0x0, link = {qre_next = 0xf00000001, qre_prev = 0x4c3a3}}, lock_order = (malloc_mutex_address_ordered | unknown: 102999814)}}

```

It's a bit like #1143 , but there is no sized deallocation here, pure C program.

**Comment by interwq** [comment]
We have seen a number of times the mutex metadata got messed up from heap corruption (e.g. because of double-free etc). Best suggestion is to try Address Sanitizer or jemalloc debug build.

**Comment by chk-jxcn** [comment]
> We have seen a number of times the mutex metadata got messed up from heap corruption (e.g. because of double-free etc). Best suggestion is to try Address Sanitizer or jemalloc debug build.

Thank you, another question, I saw that, write-after-free could be detect if enable debug and enable fill, what's the time jemalloc know it and breakout? Next malloc call or next malloc on this memory area?
