### ISSUE TITLE
QUESTION: Accidentally lead to dead loop in 'new'

### ISSUE THREAD

**Issue by lostpigxx** [jemalloc/jemalloc#2100]
In my code, we just do a simple 'new' operation like 

```c++
    auto p = new char[MAX_SIZE];
    // Do somethings
```

Accidentally it will running into a deadloop. The 'new' operation do not return. By 'top' we can see the cpu load is 99.9%. 

I have tried 'pstack' for several times and got the same results. It seems to run into a dead loop in 'extent_heap_first'.

The only things may related to our usage of jemalloc is, recently we have change the startup parameter of jemalloc since we find that the memory usage is hard to limited in our docker environment. So we disable the huge page and it is solved.

Here is the MALLOC_CONF:

`MALLOC_CONF=thp:never,metadata_thp:disabled,dirty_decay_ms:2000,muzzy_decay_ms:0,background_thread:true,oversize_threshold:4194304`

I don't know if there is a connection between them.

Has anyone ever seen such a problem before? If so, can you provide some information about it? Thanks!

Here is the stack infos of our program. 

```
#0  0x00007fa9a6acbfee in extent_ad_comp (b=0x7fa5e2aead40, a=0x7fa5e2aead40) at include/jemalloc/internal/extent_inlines.h:464
#1  extent_snad_comp (b=0x7fa5e2aead40, a=0x7fa5e2aead40) at include/jemalloc/internal/extent_inlines.h:484
#2  extent_heap_first (ph=ph@entry=0x7fa930803278) at src/extent.c:283
#3  0x00007fa9a6acf552 in extents_first_fit_locked (tsdn=0x7fa96cae2ea8, arena=0x7fa9308008c0, size=69632, extents=0x7fa9308031a8) at src/extent.c:464
#4  extents_fit_locked (tsdn=0x7fa96cae2ea8, arena=0x7fa9308008c0, alignment=64, esize=69632, extents=0x7fa9308031a8) at src/extent.c:503
#5  extent_recycle_extract (growing_retained=<optimized out>, slab=<optimized out>, alignment=<optimized out>, pad=<optimized out>, size=<optimized out>, new_addr=<optimized out>, extents=0x7fa9308031a8, rtree_ctx=<optimized out>, r_extent_hooks=<optimized out>, arena=<optimized out>, tsdn=0x7fa96cae2ea8) at src/extent.c:939
#6  extent_recycle (tsdn=tsdn@entry=0x7fa96cae2ea8, arena=arena@entry=0x7fa9308008c0, r_extent_hooks=r_extent_hooks@entry=0x7fa96cac6080, extents=extents@entry=0x7fa9308031a8, new_addr=new_addr@entry=0x0, size=size@entry=65536, pad=4096, alignment=64, slab=false, szind=44, zero=0x7fa96cac60d7, commit=0x7fa96cac607f, growing_retained=false) at src/extent.c:1141
#7  0x00007fa9a6acf928 in extents_alloc (tsdn=tsdn@entry=0x7fa96cae2ea8, arena=arena@entry=0x7fa9308008c0, r_extent_hooks=r_extent_hooks@entry=0x7fa96cac6080, extents=extents@entry=0x7fa9308031a8, new_addr=new_addr@entry=0x0, size=size@entry=65536, pad=4096, alignment=64, slab=false, szind=44, zero=0x7fa96cac60d7, commit=0x7fa96cac607f) at src/extent.c:545
#8  0x00007fa9a6a90019 in arena_extent_alloc_large (tsdn=tsdn@entry=0x7fa96cae2ea8, arena=arena@entry=0x7fa9308008c0, usize=usize@entry=65536, alignment=alignment@entry=64, zero=zero@entry=0x7fa96cac60d7) at src/arena.c:438
#9  0x00007fa9a6ad30c7 in large_palloc (zero=169, alignment=64, usize=65536, arena=0x7fa9308008c0, tsdn=0x7fa96cae2ea8) at src/large.c:47
#10 large_malloc (tsdn=tsdn@entry=0x7fa96cae2ea8, arena=<optimized out>, usize=65536, zero=zero@entry=169) at src/large.c:17
#11 0x00007fa9a6a9404f in arena_malloc_hard (tsdn=tsdn@entry=0x7fa96cae2ea8, arena=<optimized out>, arena@entry=0x0, size=size@entry=65536, ind=ind@entry=44, zero=zero@entry=false) at src/arena.c:1528
#12 0x00007fa9a6a86ad0 in arena_malloc (slow_path=false, tcache=0x7fa96cae3098, zero=false, ind=44, size=65536, arena=0x0, tsdn=<optimized out>) at include/jemalloc/internal/arena_inlines_b.h:176
#13 iallocztm (slow_path=false, arena=0x0, is_internal=false, tcache=0x7fa96cae3098, zero=false, ind=44, size=65536, tsdn=<optimized out>) at include/jemalloc/internal/jemalloc_internal_inlines_c.h:53
#14 imalloc_no_sample (ind=44, usize=65536, size=65536, tsd=0x7fa96cae2ea8, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:1949
#15 imalloc_body (tsd=0x7fa96cae2ea8, dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2149
#16 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:2258
#17 malloc_default (size=65536) at src/jemalloc.c:2289
#18 0x00007fa9a6b01019 in newImpl<false> (size=65536) at src/jemalloc_cpp.cpp:78
#19 operator new[] (size=size@entry=65536) at src/jemalloc_cpp.cpp:92
```

**Comment by davidtgoldblatt** [comment]
Almost always, infinite loops in these functions are caused by heap corruption (a double-free causes a linked list to become circularly linked). The best next step would be to try some sort of heap bug detector; preferably something like address sanitizer or valgrind, but perhaps also jemalloc configured with debug mode turned on.

**Comment by lostpigxx** [comment]
Thanks a lot!  XD
