### ISSUE TITLE
solana-validator 1.6.25 crash

### ISSUE THREAD

**Issue by zhp1254** [jemalloc/jemalloc#2135]
1、solana-validator can not started

2、error-log
[2021-09-28T11:27:49.204707063Z INFO  solana_metrics::metrics] host id: 3PWJ6hio7njDpkScXzmJdjdU2kxwaREp9bqrUWNBNbUH
[2021-09-28T11:27:49.204775683Z INFO  solana_perf::perf_libs] perf-libs found at "/data/coin/sol/releases/solana-release/bin/perf-libs"
[2021-09-28T11:27:49.204790907Z INFO  solana_perf::perf_libs] Using CUDA_HOME: "/usr/local/cuda-10.2/"
[2021-09-28T11:27:49.204805731Z INFO  solana_perf::perf_libs] setting ld_library_path to: "/usr/local/cuda-10.2/lib64:/usr/local/cuda/lib64"
[2021-09-28T11:27:49.204817730Z INFO  solana_perf::perf_libs] Loading "/data/coin/sol/releases/solana-release/bin/perf-libs/cuda-10.2/libcuda-crypt.so"
[2021-09-28T11:27:49.204996424Z INFO  solana_ledger::entry] Loading "libpoh-simd.so"
[2021-09-28T11:27:49.205022358Z INFO  solana_perf::perf_libs] perf-libs found at "/data/coin/sol/releases/solana-release/bin/perf-libs"
[2021-09-28T11:27:49.205031778Z INFO  solana_perf::perf_libs] setting ld_library_path to: "/data/coin/sol/releases/solana-release/bin/perf-libs:/usr/local/cuda-10.2/lib64:/usr/local/cuda/lib64"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', Segmentation fault (core dumped)

3、start command 
solana-validator \
    --identity ./keypairs/validator-keypair.json \
    --ledger ./validator-ledger \
    --rpc-port 8899 \
    --private-rpc \
    --no-port-check \
    --dynamic-port-range 8000-8010 \
    --trusted-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2\
    --trusted-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
    --trusted-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
    --trusted-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
    --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
    --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
    --wal-recovery-mode skip_any_corrupted_record \
    --snapshot-compression none \
    --snapshot-interval-slots 0 \
    --no-voting \
    --no-untrusted-rpc \
    --log - \
    --enable-rpc-bigtable-ledger-storage \
    --enable-rpc-transaction-history \
    --enable-bigtable-ledger-upload \
    --enable-cpi-and-log-storage \
    --cuda \

4、uname -a
Linux sol01 5.11.0-1017-aws #18~20.04.1-Ubuntu SMP Fri Aug 27 11:21:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

5、free -h
              total        used        free      shared  buff/cache   available
Mem:          124Gi       536Mi       114Gi       3.0Mi       9.0Gi       122Gi
Swap:            0B          0B          0B

6、df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        39G   16G   23G  41% /
devtmpfs         63G     0   63G   0% /dev
tmpfs            63G     0   63G   0% /dev/shm
tmpfs            13G  1.1M   13G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            63G     0   63G   0% /sys/fs/cgroup
/dev/nvme1n1    2.0T 1007M  1.9T   1% /data

7、nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

8、solana-validator  --version
solana-validator 1.6.25 (src:7de8a55b; feat:3623616870)

**Comment by zhp1254** [comment]
or this error
[2021-09-28T11:41:40.994303484Z INFO  solana_metrics::metrics] host id: 3PWJ6hio7njDpkScXzmJdjdU2kxwaREp9bqrUWNBNbUH
[2021-09-28T11:41:40.994364258Z INFO  solana_perf::perf_libs] perf-libs found at "/data/coin/sol/releases/solana-release/bin/perf-libs"
[2021-09-28T11:41:40.994376062Z INFO  solana_perf::perf_libs] Using CUDA_HOME: "/usr/local/cuda-10.2/"
[2021-09-28T11:41:40.994384758Z INFO  solana_perf::perf_libs] setting ld_library_path to: "/usr/local/cuda-10.2/lib64:/usr/local/cuda/lib64"
[2021-09-28T11:41:40.994393134Z INFO  solana_perf::perf_libs] Loading "/data/coin/sol/releases/solana-release/bin/perf-libs/cuda-10.2/libcuda-crypt.so"
[2021-09-28T11:41:40.994564265Z INFO  solana_ledger::entry] Loading "libpoh-simd.so"
[2021-09-28T11:41:40.994585567Z INFO  solana_perf::perf_libs] perf-libs found at "/data/coin/sol/releases/solana-release/bin/perf-libs"
[2021-09-28T11:41:40.994592023Z INFO  solana_perf::perf_libs] setting ld_library_path to: "/data/coin/sol/releases/solana-release/bin/perf-libs:/usr/local/cuda-10.2/lib64:/usr/local/cuda/lib64"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', streamer/src/streamer.rs:167:10
stack backtrace:
thread 'solana-receiver' panicked at 'cudaHostRegister error: 35 ptr: 0x7fcdfa3fe200 bytes: 167936', perf/src/cuda_runtime.rs:33:17

**Comment by Lapenkov** [comment]
Ok, what does it have to do with jemalloc?

**Comment by Lapenkov** [comment]
Feel free to reopen if you have anything suggesting that it's misbehaving jemalloc that causes the crashes. From the information that you've provided, I can't see why you suspect that jemalloc is the root cause.
