### ISSUE TITLE
Potential false positive in edbfe6912c1b7e8b561dfee1b058425de6c06285 ?

### ISSUE THREAD

**Issue by jbenoist** [jemalloc/jemalloc#2320]
I've been chasing this clang+asan report in `zeromq` (git tag`v4.3.4`) with `jemalloc-5.3.0`.

This simple program creates a socket, binds it, ands frees things.
```
$ cat zmq.c
#include <zmq.h>
#include <stdlib.h>
#include <assert.h>
int main(void)
{
  int rc;
  void *ctx;
  ctx = zmq_init(1);
  assert(ctx != NULL);
  void *sock = zmq_socket(ctx, ZMQ_PUB);
  assert(sock != NULL);
  rc = zmq_bind(sock, "ipc:///tmp/queue");
  assert(rc == 0);
  rc = zmq_close(sock);
  assert(rc == 0);
  rc = zmq_ctx_destroy(ctx);
  assert(rc == 0);
}
```
The report
```
$ clang --version | head -n1
clang version 14.0.6
$ clang -O0 -Wall -fsanitize=address -Wno-address-of-packed-member zmq.c -lzmq -ljemalloc
$ ./a.out
=================================================================
==1092703==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x7fd381e36080 in thread T0
    #0 0x5645a443af92 in __interceptor_free.part.0 asan_malloc_linux.cpp.o
    #1 0x7fd384cd87e4  (/usr/lib/libzmq.so.5+0x617e4) (BuildId: 5590d475bfb0155a43a46abc111f55571d66d2d6)
    #2 0x5645a447fecf in main (/home/_/a.out+0x118ecf)
    #3 0x7fd38463c2cf  (/usr/lib/libc.so.6+0x232cf) (BuildId: 9c28cfc869012ebbd43cdb0f1eebcd14e1b8bdd8)
    #4 0x7fd38463c389 in __libc_start_main (/usr/lib/libc.so.6+0x23389) (BuildId: 9c28cfc869012ebbd43cdb0f1eebcd14e1b8bdd8)
    #5 0x5645a43870d4 in _start /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115

Address 0x7fd381e36080 is a wild pointer inside of access range of size 0x000000000001.
SUMMARY: AddressSanitizer: bad-free asan_malloc_linux.cpp.o in __interceptor_free.part.0
==1092703==ABORTING
```
According to `addr2line`, the violation occurs [here](https://github.com/zeromq/libzmq/blob/master/src/socket_base.cpp#L550).

Note: No such issue with `gcc-12.2.0+asan` or `clang-14.0.6+asan`+`jemalloc-5.2.1`.

A bissection indicates that this was introduced by commit `edbfe6912c1b7e8b561dfee1b058425de6c06285` and I can confirm that this vanishes with this changeset reverted.

**Comment by interwq** [comment]
ASAN cannot work with other allocators since it packs its own to control the memory layout. That commit just happens to make the malloc function not visible at runtime. Reverting that makes it possible for asan to overload malloc on the fly. But either way it's not really using jemalloc or ASAN.

**Comment by jbenoist** [comment]
Thanks for the explanation @interwq.
