### ISSUE TITLE
prof-gcc backtrace error

### ISSUE THREAD

**Issue by guangli-dai** [jemalloc/jemalloc#2328]
When configured to prof-gcc, the backtrace may fail with error `Segmentation fault (core dumped)`
The test program is:
```
#include <stdlib.h>
#include <stdio.h>

int
main(int argc, char **argv) {
        printf("Test.\n");
        return 0;
}
```
The compiling and executing commands:
```
cc stack_bt_test.c -o stack_bt_test -I`jemalloc-config --includedir` \
-L`jemalloc-config --libdir` -Wl,-rpath,`jemalloc-config --libdir` \
-ljemalloc `jemalloc-config --libs` -g
export LD_PRELOAD=`jemalloc-config --libdir`/libjemalloc.so.`jemalloc-config --revision` app
MALLOC_CONF=stats_print:true,prof:true ./stack_bt_test
```

When backtracing, the segmentation fault always occurs when invoking function [`__builtin_return_address`](https://gcc.gnu.org/onlinedocs/gcc/Return-Address.html). Similar faults are not observed under libgcc or unwind mode. Thus, the issue should be relevant with the gcc compiler. The gcc compiler used when observing the fault is:
```
cc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-15)
```

System information:
```
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

Hardware information:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) D-2191A CPU @ 1.60GHz
```

This error will also cause the same segmentation fault when running test prof_active using
`sh test/test.sh test/unit/prof_active`. Yet similar faults are not observed during online [travis tests](https://app.travis-ci.com/github/jemalloc/jemalloc/jobs/582293648) for unit test prof_active. The reason may be that travis uses [focal with gcc 9.3.0](https://docs.travis-ci.com/user/reference/focal/).

**Comment by interwq** [comment]
For the repro program, I'd suggest not use anything jemalloc related, but instead manually create a similar function chain and call the build in utility then.

Also it's helpful to share the full stack trace too.

**Comment by guangli-dai** [comment]
> For the repro program, I'd suggest not use anything jemalloc related, but instead manually create a similar function chain and call the build in utility then.
> 
> Also it's helpful to share the full stack trace too.

Updated the program and here is the full stack trace, together with the error message, retrieved from gdb:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff792db0f in prof_backtrace_impl (vec=0x7ffff62090b8, len=0x7fffffffd288, max_len=128)
    at src/prof_sys.c:136
136		BT_FRAME(9)
(gdb) bt
#0  0x00007ffff792db0f in prof_backtrace_impl (vec=0x7ffff62090b8, len=0x7fffffffd288, 
    max_len=128) at src/prof_sys.c:136
#1  0x00007ffff793c95d in je_prof_backtrace (tsd=0x7ffff7fe6738, bt=0x7fffffffd280)
    at src/prof_sys.c:284
#2  0x00007ffff7908279 in je_prof_tctx_create (tsd=0x7ffff7fe6738) at src/prof.c:195
#3  0x00007ffff78782e6 in prof_alloc_prep (tsd=0x7ffff7fe6738, prof_active=true, 
    sample_event=true) at include/jemalloc/internal/prof_inlines.h:141
#4  0x00007ffff7882acc in imalloc_body (sopts=0x7fffffffd3f0, dopts=0x7fffffffd3b0, 
    tsd=0x7ffff7fe6738) at src/jemalloc.c:2562
#5  0x00007ffff788303f in imalloc (sopts=0x7fffffffd3f0, dopts=0x7fffffffd3b0)
    at src/jemalloc.c:2706
#6  0x00007ffff78830ac in je_malloc_default (size=72704) at src/jemalloc.c:2734
#7  0x00007ffff7877862 in imalloc_fastpath (size=72704, 
    fallback_alloc=0x7ffff7883041 <je_malloc_default>)
    at include/jemalloc/internal/jemalloc_internal_inlines_c.h:266
#8  0x00007ffff78831d6 in malloc (size=72704) at src/jemalloc.c:2758
#9  0x00007ffff71e0c1a in _GLOBAL__sub_I_eh_alloc.cc () from /lib64/libstdc++.so.6
#10 0x00007ffff7de3e0a in call_init (l=<optimized out>, argc=argc@entry=1, 
    argv=argv@entry=0x7fffffffd568, env=env@entry=0x7fffffffd578) at dl-init.c:72
#11 0x00007ffff7de3f0a in call_init (env=0x7fffffffd578, argv=0x7fffffffd568, argc=1, 
    l=<optimized out>) at dl-init.c:30
#12 _dl_init (main_map=0x7ffff7ffe1f0, argc=1, argv=0x7fffffffd568, env=0x7fffffffd578)
    at dl-init.c:119
#13 0x00007ffff7dd501a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#14 0x0000000000000001 in ?? ()
#15 0x00007fffffffd8b6 in ?? ()
#16 0x0000000000000000 in ?? ()
```

**Comment by interwq** [comment]
I meant not LD_PRELOAD jemalloc as well, so that we have a minimal repro case with no external dependencies. Then in your code directly call function __builtin_return_address, likely you will need to create a call path with similar stack depth.

**Comment by guangli-dai** [comment]
Another sample program that simply calls __builtin_return_address and causes segmentation fault:
```
#include <stdlib.h>
#include <stdio.h>
#define BT_FRAME(i) {                                           \
        void *p;                                                \
        if (__builtin_frame_address(i) == 0) {                  \
                return;                                         \
        }                                                       \
        p = __builtin_return_address(i);                        \
        if (p == NULL) {                                        \
                return;                                         \
        }                                                       \
        printf("%p\n", p);                                      \
}                                                               \


void test() {
        printf("Testing.\n");
        BT_FRAME(0)
        BT_FRAME(1)
        BT_FRAME(2)
        BT_FRAME(3)
        BT_FRAME(4)
        BT_FRAME(5)
        BT_FRAME(6)
        BT_FRAME(7)
        BT_FRAME(8)
        BT_FRAME(9)
}
void test_outer() {
        test();
}
int
main(int argc, char **argv) {
        test_outer();

        return 0;
}
```
Compile with no extra options, fault and backtrace info are as below:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000400700 in test ()
(gdb) bt
#0  0x0000000000400700 in test ()
#1  0x0000000000400943 in test_outer ()
#2  0x000000000040095f in main ()
```

**Comment by interwq** [comment]
Thanks Guangli. One last thing: maybe try the minimal repro on CI and see if it works there? Maybe trying it in tests/unit/a0.

**Comment by guangli-dai** [comment]
A minimal repro on CI in [Windows](https://app.travis-ci.com/github/jemalloc/jemalloc/jobs/582437817#L1722). This case shows exactly the same segmentation fault within the new a0.

**Comment by interwq** [comment]
@guangli-dai sorry I probably wasn't clear before -- I was more interested in if the minimal repro works fine in our Linux CI, as my understand was the jemalloc unit test passes there but fails in our dev machine. So I was thinking to make sure the minimal repro behaves exactly the same as our unit test.

**Comment by guangli-dai** [comment]
Exactly, there were no errors before so the minimal repro should still work fine. Yet there always are compiling errors caused by -Werrors. I am trying to remove the Werrors, but now it is still stuck in the build time. As for the minimal repro failure in Windows CI, that's a small surprise that has not been observed before but most possibly caused by __builtin_return_address as well so just documented it above.

**Comment by interwq** [comment]
For that specific Windows config, it's using MinGW so that's another layer in addition to gcc. So yeah no need to focus on that for now. Please do make sure the minimal repro passes on the Linux CIs, so that it fits our suspicion -- it's an older libgcc unwinder issue that doesn't happen with newer gcc on the CIs.

**Comment by guangli-dai** [comment]
I have added the minimal repro into the [unit test](https://github.com/jemalloc/jemalloc/pull/2326). In the Linux CIs, some cases are working fine (with the newly added a0 passed), some show exactly the same segmentation fault when running the minimal repro. When executed again, the CIs' results are consistent, tests under certain configurations always fail. Here are the [first test](https://app.travis-ci.com/github/jemalloc/jemalloc/builds/255470452) and the [second test](https://app.travis-ci.com/github/jemalloc/jemalloc/builds/255525252).
