### ISSUE TITLE
[coredump] Segment fault in version 5.2.1

### ISSUE THREAD

**Issue by xy720** [jemalloc/jemalloc#2556]
In version 5.2.1, we have frequently discovered this core dump in our service:

```
Core was generated by `/usr/local/service/doris/lib/be/doris_be'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  extent_szind_set (szind=36, extent=0x0) at ../include/jemalloc/internal/extent_inlines.h:261
261     ../include/jemalloc/internal/extent_inlines.h: No such file or directory.
[Current thread is 1 (LWP 989118)]
(gdb) bt
#0  extent_szind_set (szind=36, extent=0x0) at ../include/jemalloc/internal/extent_inlines.h:261
#1  arena_prof_demote (ptr=0x7f5b5c0008c0, extent=0x0, tsdn=0x7f5ba07f0180) at ../src/arena.c:1585
#2  je_arena_dalloc_promoted (tsdn=0x7f5ba07f0180, ptr=0x7f5b5c0008c0, tcache=0x0, slow_path=<optimized out>) at ../src/arena.c:1604
#3  0x0000562af6906282 in arena_dalloc_large_no_tcache (szind=<optimized out>, ptr=0x7f5b5c0008c0, tsdn=0x7f5ba07f0180)
    at ../include/jemalloc/internal/arena_inlines_b.h:234
#4  arena_dalloc_large_no_tcache (szind=<optimized out>, ptr=0x7f5b5c0008c0, tsdn=0x7f5ba07f0180)
    at ../include/jemalloc/internal/arena_inlines_b.h:232
#5  arena_dalloc_no_tcache (tsdn=0x7f5ba07f0180, ptr=0x7f5b5c0008c0) at ../include/jemalloc/internal/arena_inlines_b.h:265
#6  0x0000562af691838a in arena_dalloc (slow_path=true, alloc_ctx=<synthetic pointer>, tcache=0x0, ptr=0x7f5b5c0008c0, 
    tsdn=0x7f5ba07f0180) at ../include/jemalloc/internal/arena_inlines_b.h:292
#7  idalloctm (slow_path=true, is_internal=false, alloc_ctx=<synthetic pointer>, tcache=0x0, ptr=0x7f5b5c0008c0, tsdn=0x7f5ba07f0180)
    at ../include/jemalloc/internal/jemalloc_internal_inlines_c.h:118
#8  ifree (slow_path=true, tcache=0x0, ptr=0x7f5b5c0008c0, tsd=0x7f5ba07f0180) at ../src/jemalloc.c:2589
#9  je_free_default (ptr=0x7f5b5c0008c0) at ../src/jemalloc.c:2799
#10 0x00007f5e8d54d8e9 in _dl_deallocate_tls () from /lib64/ld-linux-x86-64.so.2
#11 0x00007f5e8c837ee7 in __free_stacks () from /lib64/libpthread.so.0
#12 0x00007f5e8c837fff in __deallocate_stack () from /lib64/libpthread.so.0
#13 0x00007f5e8c838f85 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f5e8cb4b9fd in clone () from /lib64/libc.so.6
```

![image](https://github.com/jemalloc/jemalloc/assets/22125576/41c8e468-ff41-446f-b4b1-0e31e1ce92e5)

**Comment by interwq** [comment]
> #10 0x00007f5e8d54d8e9 in _dl_deallocate_tls () from /lib64/ld-linux-x86-64.so.2
#11 0x00007f5e8c837ee7 in __free_stacks () from /lib64/libpthread.so.0
#12 0x00007f5e8c837fff in __deallocate_stack () from /lib64/libpthread.so.0

This is the thread termination path, and the crash site means jemalloc doesn't recognize the pointer, i.e. they were not allocated through jemalloc. Maybe try a newer version of libpthread? No known issue from jemalloc around this.
