### ISSUE TITLE
Segfault in `prof_free_sampled_object`

### ISSUE THREAD

**Issue by teskje** [jemalloc/jemalloc#2662]
We are using jemalloc with profiling enabled and sometimes encounter segfaults in `prof_free_sampled_object`. The segfaults always occur at the same place and they disappear when profiling is disabled, which raises the suspicion that they are caused by a race in the profiling code, rather than an unrelated memory corruption.

I'm unfortunately not able to provide a simple repro. The segfault only occurs in our system under end-to-end chaos testing, not reliably. The setup required is significant and I doubt folk here want to go through the trouble. I'll provide as much detail as I can:

* We are using jemalloc on aarch64. I haven't tested whether the segfault also occurs with x86.
* Our codebase is written in Rust and we are pulling in jemalloc through the [jemallocator](https://crates.io/crates/jemallocator) bindings crate. It's possible that this crate calls into jemalloc in a way that's incorrect or not intended.
* Our code is heavily multi-threaded.
* The segfault occurs on the current dev branch, but also in version 5.3.0

Here is part of the backtrace:

```
#0  0x0000aaaab33b7170 in _rjem_je_prof_free_sampled_object (tsd=tsd@entry=0xffff4ddeb110, ptr=ptr@entry=0xffff90636000, usize=usize@entry=4096, prof_info=prof_info@entry=0xffff4dde98f8)
    at src/prof.c:194
#1  0x0000aaaab336e7c8 in prof_free (alloc_ctx=<synthetic pointer>, usize=4096, ptr=0xffff90636000, tsd=0xffff4ddeb110) at include/jemalloc/internal/prof_inlines.h:284
#2  ifree (slow_path=false, tcache=0xffff4ddeb470, ptr=0xffff90636000, tsd=0xffff4ddeb110) at src/jemalloc.c:2920
#3  _rjem_je_free_default (ptr=0xffff90636000) at src/jemalloc.c:3028
#4  0x0000aaaab336efb4 in je_free_impl (ptr=0xffff90636000) at include/jemalloc/internal/jemalloc_internal_inlines_c.h:593
#5  0x0000ffff90b5cecc in __run_exit_handlers (status=2, listp=0xffff90cbb730 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at ./stdlib/exit.c:128
#6  0x0000ffff90b5cf0c in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143
#7  0x0000aaaab3152898 in std::sys::pal::unix::os::exit () at library/std/src/sys/pal/unix/os.rs:750
#8  0x0000aaaab314bc84 in std::process::exit () at library/std/src/process.rs:2290
```

The segfault occurs on this line:
https://github.com/jemalloc/jemalloc/blob/21bcc0a8d49ab2944ae53c7e43f5c84fc8a34322/src/prof.c#L194

Inspecting with gdb I can see that `tctx->tdata` is NULL. I also confirmed this by adding additional asserts directly before this line. Both of these fail:

```c
assert(tctx->tdata != NULL);
assert(tctx->cnts.curobjs > 0);
```

The `curobjs` assert is also performed after the segfaulting line, so this value being 0 is unexpected. `curobjs == 0` allows the `tctx` to be destroyed by `prof_tctx_try_destroy`, which is also the only place I found that sets `tctx->tdata` to NULL.

I'm not familiar enough with the jemalloc code to debug further. But happy to dig for more clues if people have ideas!

**Comment by teskje** [comment]
Turns out that this is likely to be caused by a double free, rather than an issue with jemalloc.
