### ISSUE TITLE
'Bus error' on FreeBSD 9.3 (4.0.4)

### ISSUE THREAD

**Issue by sennoma** [jemalloc/jemalloc#440]
Program terminated with signal 10, Bus error.

Back-trace: 
```
#0  0x0000000802a683bc in je_arena_tcache_fill_small (arena=<value optimized out>, tbin=0x94636b1a0, binind=<value optimized out>, prof_accumbytes=<value optimized out>) at bitmap.h:147
	run = (arena_run_t *) 0x97f808ed0
	ptr = <value optimized out>
	i = 0
	nfill = 8
	bin = (arena_bin_t *) 0x9468220d0
#1  0x0000000802a8f2d4 in je_tcache_alloc_small_hard (tsd=<value optimized out>, arena=<value optimized out>, tcache=<value optimized out>, tbin=0x94636b1a0, binind=<value optimized out>) at src/tcache.c:79
	ret = <value optimized out>
#2  0x0000000802a5d331 in malloc (size=<value optimized out>) at tcache.h:280
	ret = <value optimized out>
	usize = 256
#3  0x0000000001f4af7d in operator new (sz=256) at ../../.././../gcc-4.4.7/libstdc++-v3/libsupc++/new_op.cc:52
	p = <value optimized out>
```
Registers:
```
rax            0x8000000000000000	-9223372036854775808
rbx            0x802c9dce0	34406522080
rcx            0x3f	63
rdx            0x3ffffffffffffff	288230376151711743
rsi            0x97f808ed0	40793837264
rdi            0xffffffffffffffff	-1
rbp            0x0	0x0
rsp            0x7ffffd598af0	0x7ffffd598af0
r8             0x0	0
r9             0x1	1
r10            0x94636b1a0	39832695200
r11            0x8000000000000000	-9223372036854775808
r12            0x7	7
r13            0x1	1
r14            0x94636b1a0	39832695200
r15            0xffffffffffffffff	-1
rip            0x802a683bc	0x802a683bc <je_arena_tcache_fill_small+636>
eflags         0x10286	66182
cs             0x43	67
ss             0x3b	59
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```
Environment:
```
jemaloc version: 4.0.4
OS: FreeBSD 9.3-RELEASE-p24 amd64
Process size in memory before crash: ~5.7 GB
Process uptime: ~22 hours
````

**Comment by jasone** [comment]
This is likely an application bug.  If you determine otherwise, please reopen with enough information to make diagnosis feasible.

**Comment by jiawangxi** [comment]
I have come with the same problem recently, Did you finally find out the problem?
