### ISSUE TITLE
TSD issue with jemalloc 4.2.0 or newer

### ISSUE THREAD

**Issue by cparaschiv** [jemalloc/jemalloc#514]
With jemalloc 4.2.0 or newer (i.e., including latest dev commit, 32127949a3), I'm hitting the following error on a PowerPC platform (i.e., PPC750) with LinuxThreads (i.e., I configure jemalloc with '--disable-tls'):

<jemalloc>: Error setting TSD for 

The issue is not reproducible with 4.1.1. Nonetheless, if I configure jemalloc with '--enable-debug', I get the following error with 4.1.1 / 4.1.0 / 4.0.4 / 4.0.0, but not with 3.6.0:

<jemalloc>: ../../src/jemalloc-4.x/include/jemalloc/internal/tsd.h:609: Failed assertion: "tsd_booted"

If I don't configure jemalloc with '--enable-debug', my application starts just fine with all of the aforementioned versions, 4.0.0 -> 4.1.1.

Both issues are always reproducible, so please tell me if I can help with other information.

**Comment by jasone** [comment]
I'm guessing that b2c0d6322d2307458ae2b28545f8a5c9903d7ef5 is to blame.

**Comment by jasone** [comment]
@cparaschiv, ideally we would get a fix for this into the 4.4.0 release, but it's not obvious to me exactly what the problem is, so I either need a patch from you or more detail (backtraces and/or repro steps).  Do you have time to look at this over the next week?

**Comment by cparaschiv** [comment]
The issue also happens with jemalloc 4.4.0 and can be reproduced with the following steps:

```
$ cat test.c
#include "jemalloc.h"

int main(void)
{
    return 0;
}
$ /opt/cegl-3.2/powerpc-750-linux-gnu/gcc-4.2.4-glibc-2.3.3/bin/powerpc-750-linux-gnu-gcc test.c -o test -L. -ljemalloc
$ /opt/cegl-3.2/powerpc-750-linux-gnu/gcc-4.2.4-glibc-2.3.3/bin/powerpc-750-linux-gnu-objdump -p test | grep NEEDED
  NEEDED      libjemalloc.so.2
  NEEDED      libc.so.6
```

Then I copy the binary on the target and run it:

```
bash-4.1# ./test
<jemalloc>: Error setting TSD for 
Aborted
```

As I've said, this is a PowerPC platform (i.e., PPC750) with LinuxThreads (i.e., I configure jemalloc with '--disable-tls').

**Comment by cparaschiv** [comment]
I configured jemalloc with '--enable-debug' and ran under GDB:

```
(gdb) run
Starting program: /test 
[Thread debugging using libthread_db enabled]
<jemalloc>: Error setting TSD for 

Program received signal SIGABRT, Aborted.
0x0fe36938 in kill () from /lib/libc.so.6
(gdb) bt
#0  0x0fe36938 in kill () from /lib/libc.so.6
#1  0x0fcd37a4 in pthread_kill () from /lib/libpthread.so.0
#2  0x0fcd3c8c in raise () from /lib/libpthread.so.0
#3  0x0fe36724 in raise () from /lib/libc.so.6
#4  0x0fe37d2c in abort () from /lib/libc.so.6
#5  0x0ffcc1e4 in je_tsd_wrapper_set () from /usr/lib/libjemalloc.so.2
#6  0x0ffcc39c in je_tsd_boot0 () from /usr/lib/libjemalloc.so.2
#7  0x0ffcded8 in je_malloc_tsd_boot0 () from /usr/lib/libjemalloc.so.2
#8  0x0ff6eed4 in malloc_init_hard () from /usr/lib/libjemalloc.so.2
#9  0x0ff6ae54 in malloc_init () from /usr/lib/libjemalloc.so.2
#10 0x0ff6f2e0 in ialloc_body () from /usr/lib/libjemalloc.so.2
#11 0x0ff70294 in calloc () from /usr/lib/libjemalloc.so.2
#12 0x0fcd3f8c in pthread_setspecific () from /lib/libpthread.so.0
#13 0x0ffcc1cc in je_tsd_wrapper_set () from /usr/lib/libjemalloc.so.2
#14 0x0ffcc39c in je_tsd_boot0 () from /usr/lib/libjemalloc.so.2
#15 0x0ffcded8 in je_malloc_tsd_boot0 () from /usr/lib/libjemalloc.so.2
#16 0x0ff6eed4 in malloc_init_hard () from /usr/lib/libjemalloc.so.2
#17 0x0ff6ae54 in malloc_init () from /usr/lib/libjemalloc.so.2
#18 0x0ff6f2e0 in ialloc_body () from /usr/lib/libjemalloc.so.2
#19 0x0ff70294 in calloc () from /usr/lib/libjemalloc.so.2
#20 0x0fcd3f8c in pthread_setspecific () from /lib/libpthread.so.0
#21 0x0ffcc1cc in je_tsd_wrapper_set () from /usr/lib/libjemalloc.so.2
#22 0x0ffcc39c in je_tsd_boot0 () from /usr/lib/libjemalloc.so.2
[..]
#8180 0x0fcd3f8c in pthread_setspecific () from /lib/libpthread.so.0
#8181 0x0ffcc1cc in je_tsd_wrapper_set () from /usr/lib/libjemalloc.so.2
#8182 0x0ffcc39c in je_tsd_boot0 () from /usr/lib/libjemalloc.so.2
#8183 0x0ffcded8 in je_malloc_tsd_boot0 () from /usr/lib/libjemalloc.so.2
#8184 0x0ff6eed4 in malloc_init_hard () from /usr/lib/libjemalloc.so.2
#8185 0x0ff6ae54 in malloc_init () from /usr/lib/libjemalloc.so.2
#8186 0x0ff6f2e0 in ialloc_body () from /usr/lib/libjemalloc.so.2
#8187 0x0ff70294 in calloc () from /usr/lib/libjemalloc.so.2
#8188 0x0fcd3f8c in pthread_setspecific () from /lib/libpthread.so.0
#8189 0x0ffcc1cc in je_tsd_wrapper_set () from /usr/lib/libjemalloc.so.2
#8190 0x0ffcc39c in je_tsd_boot0 () from /usr/lib/libjemalloc.so.2
#8191 0x0ffcded8 in je_malloc_tsd_boot0 () from /usr/lib/libjemalloc.so.2
#8192 0x0ff6eed4 in malloc_init_hard () from /usr/lib/libjemalloc.so.2
#8193 0x0ff6ae54 in malloc_init () from /usr/lib/libjemalloc.so.2
#8194 0x0ff740c8 in jemalloc_constructor () from /usr/lib/libjemalloc.so.2
#8195 0x0ffd3d0c in __do_global_ctors_aux () from /usr/lib/libjemalloc.so.2
#8196 0x0ff67e44 in _init () from /usr/lib/libjemalloc.so.2
#8197 0x3000c17c in call_init () from /lib/ld.so.1
#8198 0x3000c34c in _dl_init_internal () from /lib/ld.so.1
#8199 0x3000fcf8 in _start () from /lib/ld.so.1
```

This looks like a malloc bootstrapping issue, similar to what I fixed with 9cb481a73f, when malloc_tsd_boot0() was calling pthread_setspecific(), which caused recursive allocation.
