### ISSUE TITLE
Segmentation fault with jemalloc

### ISSUE THREAD

**Issue by scw00** [jemalloc/jemalloc#820]
```
(gdb) bt full
#0  0x00007ffff28550cb in __GI___clock_gettime (clock_id=6, tp=0x7fffffffe1a0) at ../sysdeps/unix/clock_gettime.c:115
        f = 0x6d87af16fc73a357
        v_ret = <optimized out>
        retval = -1
#1  0x00007ffff79ad819 in nstime_get (time=0x7ffff254cb00) at src/nstime.c:105
        ts = {tv_sec = 512, tv_nsec = 2776661090840659712}
#2  je_nstime_update (time=time@entry=0x7ffff254cb00) at src/nstime.c:158
        old_time = {ns = 0}
#3  0x00007ffff7984acc in arena_decay_reinit (decay_time=<optimized out>, extents=0x7ffff254b5e0, decay=0x7ffff254ca80)
    at src/arena.c:719
No locals.
#4  arena_decay_init (decay=decay@entry=0x7ffff254ca80, extents=extents@entry=0x7ffff254b5e0, decay_time=<optimized out>, 
    stats=stats@entry=0x7ffff25499a0) at src/arena.c:738
No locals.
#5  0x00007ffff798aa21 in je_arena_new (tsdn=tsdn@entry=0x0, ind=ind@entry=0, 
    extent_hooks=extent_hooks@entry=0x7ffff7bd0d40 <je_extent_hooks_default>) at src/arena.c:1939
        arena = 0x7ffff2549980
        base = 0x7ffff25490c0
        i = <optimized out>
#6  0x00007ffff797e7ed in arena_init_locked (extent_hooks=0x7ffff7bd0d40 <je_extent_hooks_default>, ind=0, tsdn=0x0)
    at src/jemalloc.c:421
        arena = 0x6d87af16fc73a357
        extent_hooks = 0x7ffff7bd0d40 <je_extent_hooks_default>
        ind = 0
        tsdn = 0x0
#7  je_arena_init (tsdn=tsdn@entry=0x0, ind=ind@entry=0, extent_hooks=0x7ffff7bd0d40 <je_extent_hooks_default>)
    at src/jemalloc.c:431
No locals.
#8  0x00007ffff797c953 in malloc_init_hard_a0_locked () at src/jemalloc.c:1249
No locals.
#9  0x00007ffff797c9f0 in malloc_init_hard () at src/jemalloc.c:1402
No locals.
#10 0x00007ffff79817a5 in malloc_init () at src/jemalloc.c:304
No locals.
#11 imalloc (dopts=<synthetic pointer>, sopts=<synthetic pointer>) at src/jemalloc.c:1852
No locals.
---Type <return> to continue, or q <return> to quit---
#12 calloc (num=1, size=32) at src/jemalloc.c:1985
        ret = <optimized out>
        dopts = {result = <optimized out>, num_items = 1, item_size = 32, alignment = 0, zero = <optimized out>, 
          tcache_ind = <optimized out>, arena_ind = <optimized out>}
#13 0x00007ffff3332690 in _dlerror_run (operate=operate@entry=0x7ffff3332130 <dlsym_doit>, args=args@entry=0x7fffffffe3b0)
    at dlerror.c:141
        result = <optimized out>
#14 0x00007ffff3332198 in __dlsym (handle=<optimized out>, name=<optimized out>) at dlsym.c:70
        args = {handle = 0xffffffffffffffff, name = 0x7ffff4a07305 "read", who = 0x7ffff4a05dbc, sym = 0x7ffff4e6b6a0}
        result = <optimized out>
#15 0x00007ffff4a05dbc in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.0
No symbol table info available.
#16 0x00007ffff49f89a9 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.0
No symbol table info available.
#17 0x00007ffff49fac8b in __asan_init_v1 () from /usr/lib/x86_64-linux-gnu/libasan.so.0
No symbol table info available.
#18 0x00007ffff7dea25a in _dl_init (main_map=0x7ffff7ffe1c8, argc=3, argv=0x7fffffffe4a8, env=0x7fffffffe4c8) at dl-init.c:111
        addrs = <optimized out>
        cnt = <optimized out>
        preinit_array = <optimized out>
        preinit_array_size = <optimized out>
        i = <optimized out>
#19 0x00007ffff7ddb30a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
        _dl_rtld_libname2 = {name = 0x0, next = 0x0, dont_free = 0}
        start_time = 69446031603470
        _dl_rtld_libname = {name = 0x400270 "/lib64/ld-linux-x86-64.so.2", next = 0x7ffff7ffe010 <newname>, dont_free = 0}
        library_path = 0x7fffffffed14 ":/usr/local/lib:/usr/lib:/usr/local/lib:/usr/lib"
        audit_list = 0x0
        relocate_time = 2323624
        any_debug = 0
        preloadlist = 0x7fffffffe7a6 "/usr/local/lib/libjemalloc.so.2"
        version_info = 0
        load_time = 1342863
        tls_init_tp_called = true
        _rtld_local_ro = {_dl_debug_mask = 0, _dl_osversion = 263181, _dl_platform = 0x7fffffffe6f9 "x86_64", 
          _dl_platformlen = 6, _dl_pagesize = 4096, _dl_inhibit_cache = 0, _dl_initial_searchlist = {r_list = 0x7ffff7fea938, 
---Type <return> to continue, or q <return> to quit---
            r_nlist = 17}, _dl_clktck = 100, _dl_verbose = 0, _dl_debug_fd = 2, _dl_lazy = 1, _dl_bind_not = 0, 
          _dl_dynamic_weak = 0, _dl_fpu_control = 895, _dl_correct_cache_id = 771, _dl_hwcap = 529267711, _dl_hwcap_mask = 0, 
          _dl_auxv = 0x7fffffffe5b0, _dl_inhibit_rpath = 0x0, _dl_origin_path = 0x0, _dl_use_load_bias = 18446744073709551615, 
          _dl_profile = 0x0, _dl_profile_output = 0x7ffff7df54a0 "/var/tmp", _dl_trace_prelink = 0x0, 
          _dl_trace_prelink_map = 0x0, _dl_init_all_dirs = 0x7ffff7ff75f8, _dl_hp_timing_overhead = 18, 
          _dl_sysinfo_dso = 0x7ffff7ffa000, _dl_sysinfo_map = 0x7ffff7ffe760, _dl_hwcap2 = 0, 
          _dl_debug_printf = 0x7ffff7deb080 <_dl_debug_printf>, _dl_catch_error = 0x7ffff7de9f50 <_dl_catch_error>, 
          _dl_signal_error = 0x7ffff7de9d20 <_dl_signal_error>, _dl_mcount = 0x7ffff7dec2f0 <_dl_mcount>, 
          _dl_lookup_symbol_x = 0x7ffff7de4830 <_dl_lookup_symbol_x>, _dl_check_caller = 0x7ffff7ded740 <_dl_check_caller>, 
          _dl_open = 0x7ffff7dee2d0 <_dl_open>, _dl_close = 0x7ffff7df0420 <_dl_close>, 
          _dl_tls_get_addr_soft = 0x7ffff7ded340 <_dl_tls_get_addr_soft>, 
          _dl_discover_osversion = 0x7ffff7df1800 <_dl_discover_osversion>, _dl_audit = 0x0, _dl_naudit = 0}
        _dl_skip_args = 0
        __pointer_chk_guard_local = 7892469385249661783
        _rtld_global_ro = {_dl_debug_mask = 0, _dl_osversion = 263181, _dl_platform = 0x7fffffffe6f9 "x86_64", 
          _dl_platformlen = 6, _dl_pagesize = 4096, _dl_inhibit_cache = 0, _dl_initial_searchlist = {r_list = 0x7ffff7fea938, 
            r_nlist = 17}, _dl_clktck = 100, _dl_verbose = 0, _dl_debug_fd = 2, _dl_lazy = 1, _dl_bind_not = 0, 
          _dl_dynamic_weak = 0, _dl_fpu_control = 895, _dl_correct_cache_id = 771, _dl_hwcap = 529267711, _dl_hwcap_mask = 0, 
          _dl_auxv = 0x7fffffffe5b0, _dl_inhibit_rpath = 0x0, _dl_origin_path = 0x0, _dl_use_load_bias = 18446744073709551615, 
          _dl_profile = 0x0, _dl_profile_output = 0x7ffff7df54a0 "/var/tmp", _dl_trace_prelink = 0x0, 
          _dl_trace_prelink_map = 0x0, _dl_init_all_dirs = 0x7ffff7ff75f8, _dl_hp_timing_overhead = 18, 
          _dl_sysinfo_dso = 0x7ffff7ffa000, _dl_sysinfo_map = 0x7ffff7ffe760, _dl_hwcap2 = 0, 
          _dl_debug_printf = 0x7ffff7deb080 <_dl_debug_printf>, _dl_catch_error = 0x7ffff7de9f50 <_dl_catch_error>, 
          _dl_signal_error = 0x7ffff7de9d20 <_dl_signal_error>, _dl_mcount = 0x7ffff7dec2f0 <_dl_mcount>, 
          _dl_lookup_symbol_x = 0x7ffff7de4830 <_dl_lookup_symbol_x>, _dl_check_caller = 0x7ffff7ded740 <_dl_check_caller>, 
          _dl_open = 0x7ffff7dee2d0 <_dl_open>, _dl_close = 0x7ffff7df0420 <_dl_close>, 
          _dl_tls_get_addr_soft = 0x7ffff7ded340 <_dl_tls_get_addr_soft>, 
          _dl_discover_osversion = 0x7ffff7df1800 <_dl_discover_osversion>, _dl_audit = 0x0, _dl_naudit = 0}
        _dl_argv = 0x7fffffffe4a8
        _rtld_local = {_dl_ns = {{_ns_loaded = 0x7ffff7ffe1c8, _ns_nloaded = 18, _ns_main_searchlist = 0x7ffff7ffe480, 
              _ns_global_scope_alloc = 0, _ns_unique_sym_table = {lock = {mutex = {__data = {__lock = 0, __count = 0, 
                      __owner = 0, __nusers = 0, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
                    __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, 
                entries = 0x7ffff7fe3000, size = 127, n_elements = 53, free = 0x7ffff7df1c00 <free>}, _ns_debug = {
                r_version = 0, r_map = 0x0, r_brk = 0, r_state = RT_CONSISTENT, r_ldbase = 0}}, {_ns_loaded = 0x0, 
              _ns_nloaded = 0, _ns_main_searchlist = 0x0, _ns_global_scope_alloc = 0, _ns_unique_sym_table = {lock = {mutex = {
---Type <return> to continue, or q <return> to quit---
                    __data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, 
                      __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, entries = 0x0, 
                size = 0, n_elements = 0, free = 0x0}, _ns_debug = {r_version = 0, r_map = 0x0, r_brk = 0, 
                r_state = RT_CONSISTENT, r_ldbase = 0}} <repeats 15 times>}, _dl_nns = 1, _dl_load_lock = {mutex = {__data = {
                __lock = 1, __count = 1, __owner = 13959, __nusers = 1, __kind = 1, __spins = 0, __elision = 0, __list = {
                  __prev = 0x0, __next = 0x0}}, 
              __size = "\001\000\000\000\001\000\000\000\207\066\000\000\001\000\000\000\001", '\000' <repeats 22 times>, 
              __align = 4294967297}}, _dl_load_write_lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, 
                __nusers = 0, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
              __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, _dl_load_adds = 18, 
          _dl_initfirst = 0x0, _dl_cpuclock_offset = 69446031619806, _dl_profile_map = 0x0, _dl_num_relocations = 1904, 
          _dl_num_cache_relocations = 1555, _dl_all_dirs = 0x7ffff7ff75f8, 
          _dl_error_catch_tsd = 0x7ffff2882d30 <__libc_dl_error_tsd>, _dl_rtld_map = {l_addr = 140737351884800, 
            l_name = 0x400270 "/lib64/ld-linux-x86-64.so.2", l_ld = 0x7ffff7ffce70, l_next = 0x0, l_prev = 0x7ffff7fea000, 
            l_real = 0x7ffff7ffd9f8 <_rtld_global+2456>, l_ns = 0, l_libname = 0x7ffff7ffe060 <_dl_rtld_libname>, l_info = {0x0, 
              0x0, 0x7ffff7ffcef0, 0x7ffff7ffcee0, 0x7ffff7ffce80, 0x7ffff7ffcea0, 0x7ffff7ffceb0, 0x7ffff7ffcf20, 
              0x7ffff7ffcf30, 0x7ffff7ffcf40, 0x7ffff7ffcec0, 0x7ffff7ffced0, 0x0, 0x0, 0x7ffff7ffce70, 0x0, 0x0, 0x0, 0x0, 0x0, 
              0x7ffff7ffcf00, 0x0, 0x0, 0x7ffff7ffcf10, 0x0 <repeats 12 times>, 0x7ffff7ffcf60, 0x7ffff7ffcf50, 0x0, 0x0, 
              0x7ffff7ffcf80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffff7ffcf70, 0x0 <repeats 25 times>, 0x7ffff7ffce90}, 
            l_phdr = 0x7ffff7dda040, l_entry = 0, l_phnum = 7, l_ldnum = 0, l_searchlist = {r_list = 0x0, r_nlist = 0}, 
            l_symbolic_searchlist = {r_list = 0x0, r_nlist = 0}, l_loader = 0x0, l_versions = 0x7ffff7fe8498, l_nversions = 6, 
            l_nbuckets = 17, l_gnu_bitmask_idxbits = 3, l_gnu_shift = 8, l_gnu_bitmask = 0x7ffff7dda2c0, {
              l_gnu_buckets = 0x7ffff7dda2e0, l_chain = 0x7ffff7dda2e0}, {l_gnu_chain_zero = 0x7ffff7dda31c, 
              l_buckets = 0x7ffff7dda31c}, l_direct_opencount = 0, l_type = lt_library, l_relocated = 1, l_init_called = 0, 
            l_global = 1, l_reserved = 0, l_phdr_allocated = 0, l_soname_added = 0, l_faked = 0, l_need_tls_init = 0, 
            l_auditing = 0, l_audit_any_plt = 0, l_removed = 0, l_contiguous = 0, l_symbolic_in_local_scope = 0, 
            l_free_initfini = 0, l_rpath_dirs = {dirs = 0x0, malloced = 0}, l_reloc_result = 0x0, l_versyms = 0x7ffff7dda7c4, 
            l_origin = 0x0, l_map_start = 140737351884800, l_map_end = 140737354129864, l_text_end = 140737351996560, 
            l_scope_mem = {0x0, 0x0, 0x0, 0x0}, l_scope_max = 0, l_scope = 0x0, l_local_scope = {0x0, 0x0}, l_dev = 0, 
            l_ino = 0, l_runpath_dirs = {dirs = 0x0, malloced = 0}, l_initfini = 0x0, l_reldeps = 0x0, l_reldepsmax = 0, 
            l_used = 1, l_feature_1 = 0, l_flags_1 = 0, l_flags = 0, l_idx = 0, l_mach = {plt = 0, gotplt = 0, 
              tlsdesc_table = 0x0}, l_lookup_cache = {sym = 0x7ffff7dda420, type_class = 1, value = 0x7ffff7ff7660, 
              ret = 0x7ffff79778a8}, l_tls_initimage = 0x0, l_tls_initimage_size = 0, l_tls_blocksize = 0, l_tls_align = 0, 
            l_tls_firstbyte_offset = 0, l_tls_offset = 0, l_tls_modid = 0, l_tls_dtor_count = 0, l_relro_addr = 2239488, 
            l_relro_size = 1024, l_serial = 0, l_audit = 0x7ffff7ffde68 <_rtld_global+3592>}, audit_data = {{cookie = 0, 
              bindflags = 0} <repeats 16 times>}, _dl_rtld_lock_recursive = 0x7ffff353f400 <__GI___pthread_mutex_lock>, 
---Type <return> to continue, or q <return> to quit---
          _dl_rtld_unlock_recursive = 0x7ffff35407b0 <__GI___pthread_mutex_unlock>, 
          _dl_make_stack_executable_hook = 0x7ffff353c2b0 <__make_stacks_executable>, _dl_stack_flags = 6, 
          _dl_tls_dtv_gaps = false, _dl_tls_max_dtv_idx = 4, _dl_tls_dtv_slotinfo_list = 0x7ffff7fe8528, 
          _dl_tls_static_nelem = 4, _dl_tls_static_size = 10560, _dl_tls_static_used = 6576, _dl_tls_static_align = 64, 
          _dl_initial_dtv = 0x7ffff7fe7950, _dl_tls_generation = 1, 
          _dl_init_static_tls = 0x7ffff353cc00 <__pthread_init_static_tls>, 
          _dl_wait_lookup_done = 0x7ffff353cd20 <__wait_lookup_done>, _dl_scope_free_list = 0x0}
        _rtld_global = {_dl_ns = {{_ns_loaded = 0x7ffff7ffe1c8, _ns_nloaded = 18, _ns_main_searchlist = 0x7ffff7ffe480, 
              _ns_global_scope_alloc = 0, _ns_unique_sym_table = {lock = {mutex = {__data = {__lock = 0, __count = 0, 
                      __owner = 0, __nusers = 0, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
                    __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, 
                entries = 0x7ffff7fe3000, size = 127, n_elements = 53, free = 0x7ffff7df1c00 <free>}, _ns_debug = {
                r_version = 0, r_map = 0x0, r_brk = 0, r_state = RT_CONSISTENT, r_ldbase = 0}}, {_ns_loaded = 0x0, 
              _ns_nloaded = 0, _ns_main_searchlist = 0x0, _ns_global_scope_alloc = 0, _ns_unique_sym_table = {lock = {mutex = {
                    __data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, 
                      __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, entries = 0x0, 
                size = 0, n_elements = 0, free = 0x0}, _ns_debug = {r_version = 0, r_map = 0x0, r_brk = 0, 
                r_state = RT_CONSISTENT, r_ldbase = 0}} <repeats 15 times>}, _dl_nns = 1, _dl_load_lock = {mutex = {__data = {
                __lock = 1, __count = 1, __owner = 13959, __nusers = 1, __kind = 1, __spins = 0, __elision = 0, __list = {
                  __prev = 0x0, __next = 0x0}}, 
              __size = "\001\000\000\000\001\000\000\000\207\066\000\000\001\000\000\000\001", '\000' <repeats 22 times>, 
              __align = 4294967297}}, _dl_load_write_lock = {mutex = {__data = {__lock = 0, __count = 0, __owner = 0, 
                __nusers = 0, __kind = 1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
              __size = '\000' <repeats 16 times>, "\001", '\000' <repeats 22 times>, __align = 0}}, _dl_load_adds = 18, 
          _dl_initfirst = 0x0, _dl_cpuclock_offset = 69446031619806, _dl_profile_map = 0x0, _dl_num_relocations = 1904, 
          _dl_num_cache_relocations = 1555, _dl_all_dirs = 0x7ffff7ff75f8, 
          _dl_error_catch_tsd = 0x7ffff2882d30 <__libc_dl_error_tsd>, _dl_rtld_map = {l_addr = 140737351884800, 
            l_name = 0x400270 "/lib64/ld-linux-x86-64.so.2", l_ld = 0x7ffff7ffce70, l_next = 0x0, l_prev = 0x7ffff7fea000, 
            l_real = 0x7ffff7ffd9f8 <_rtld_global+2456>, l_ns = 0, l_libname = 0x7ffff7ffe060 <_dl_rtld_libname>, l_info = {0x0, 
              0x0, 0x7ffff7ffcef0, 0x7ffff7ffcee0, 0x7ffff7ffce80, 0x7ffff7ffcea0, 0x7ffff7ffceb0, 0x7ffff7ffcf20, 
              0x7ffff7ffcf30, 0x7ffff7ffcf40, 0x7ffff7ffcec0, 0x7ffff7ffced0, 0x0, 0x0, 0x7ffff7ffce70, 0x0, 0x0, 0x0, 0x0, 0x0, 
              0x7ffff7ffcf00, 0x0, 0x0, 0x7ffff7ffcf10, 0x0 <repeats 12 times>, 0x7ffff7ffcf60, 0x7ffff7ffcf50, 0x0, 0x0, 
              0x7ffff7ffcf80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffff7ffcf70, 0x0 <repeats 25 times>, 0x7ffff7ffce90}, 
            l_phdr = 0x7ffff7dda040, l_entry = 0, l_phnum = 7, l_ldnum = 0, l_searchlist = {r_list = 0x0, r_nlist = 0}, 
            l_symbolic_searchlist = {r_list = 0x0, r_nlist = 0}, l_loader = 0x0, l_versions = 0x7ffff7fe8498, l_nversions = 6, 
            l_nbuckets = 17, l_gnu_bitmask_idxbits = 3, l_gnu_shift = 8, l_gnu_bitmask = 0x7ffff7dda2c0, {
---Type <return> to continue, or q <return> to quit---
              l_gnu_buckets = 0x7ffff7dda2e0, l_chain = 0x7ffff7dda2e0}, {l_gnu_chain_zero = 0x7ffff7dda31c, 
              l_buckets = 0x7ffff7dda31c}, l_direct_opencount = 0, l_type = lt_library, l_relocated = 1, l_init_called = 0, 
            l_global = 1, l_reserved = 0, l_phdr_allocated = 0, l_soname_added = 0, l_faked = 0, l_need_tls_init = 0, 
            l_auditing = 0, l_audit_any_plt = 0, l_removed = 0, l_contiguous = 0, l_symbolic_in_local_scope = 0, 
            l_free_initfini = 0, l_rpath_dirs = {dirs = 0x0, malloced = 0}, l_reloc_result = 0x0, l_versyms = 0x7ffff7dda7c4, 
            l_origin = 0x0, l_map_start = 140737351884800, l_map_end = 140737354129864, l_text_end = 140737351996560, 
            l_scope_mem = {0x0, 0x0, 0x0, 0x0}, l_scope_max = 0, l_scope = 0x0, l_local_scope = {0x0, 0x0}, l_dev = 0, 
            l_ino = 0, l_runpath_dirs = {dirs = 0x0, malloced = 0}, l_initfini = 0x0, l_reldeps = 0x0, l_reldepsmax = 0, 
            l_used = 1, l_feature_1 = 0, l_flags_1 = 0, l_flags = 0, l_idx = 0, l_mach = {plt = 0, gotplt = 0, 
              tlsdesc_table = 0x0}, l_lookup_cache = {sym = 0x7ffff7dda420, type_class = 1, value = 0x7ffff7ff7660, 
              ret = 0x7ffff79778a8}, l_tls_initimage = 0x0, l_tls_initimage_size = 0, l_tls_blocksize = 0, l_tls_align = 0, 
            l_tls_firstbyte_offset = 0, l_tls_offset = 0, l_tls_modid = 0, l_tls_dtor_count = 0, l_relro_addr = 2239488, 
            l_relro_size = 1024, l_serial = 0, l_audit = 0x7ffff7ffde68 <_rtld_global+3592>}, audit_data = {{cookie = 0, 
              bindflags = 0} <repeats 16 times>}, _dl_rtld_lock_recursive = 0x7ffff353f400 <__GI___pthread_mutex_lock>, 
          _dl_rtld_unlock_recursive = 0x7ffff35407b0 <__GI___pthread_mutex_unlock>, 
          _dl_make_stack_executable_hook = 0x7ffff353c2b0 <__make_stacks_executable>, _dl_stack_flags = 6, 
          _dl_tls_dtv_gaps = false, _dl_tls_max_dtv_idx = 4, _dl_tls_dtv_slotinfo_list = 0x7ffff7fe8528, 
          _dl_tls_static_nelem = 4, _dl_tls_static_size = 10560, _dl_tls_static_used = 6576, _dl_tls_static_align = 64, 
          _dl_initial_dtv = 0x7ffff7fe7950, _dl_tls_generation = 1, 
          _dl_init_static_tls = 0x7ffff353cc00 <__pthread_init_static_tls>, 
          _dl_wait_lookup_done = 0x7ffff353cd20 <__wait_lookup_done>, _dl_scope_free_list = 0x0}
        _dl_argc = 3
        _dl_argv_internal = 0x7fffffffe4a8
#20 0x0000000000000003 in ?? ()
No symbol table info available.
#21 0x00007fffffffe709 in ?? ()
No symbol table info available.
#22 0x00007fffffffe73a in ?? ()
No symbol table info available.
#23 0x00007fffffffe73d in ?? ()
No symbol table info available.
#24 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by jasone** [comment]
ASAN provides a custom allocator which is incompatible with other allocators; build without jemalloc when utilizing ASAN.
