### ISSUE TITLE
segfault with MemorySanitizer

### ISSUE THREAD

**Issue by tamird** [jemalloc/jemalloc#821]
Compiled jemalloc 4.5.0 with MSan:
```
$ CFLAGS='-fsanitize=memory -fsanitize-memory-track-origins -fno-omit-frame-pointer' LDFLAGS=-fsanitize=memory ../c-deps/jemalloc.src/configure --enable-prof
$ make -j4 build_static_lib
```

main.cc:
```c++
#include <jemalloc/jemalloc.h>

int main(int argc, char **argv) {
  malloc_stats_print(NULL,NULL,NULL);

  return 0;
}
```

```
$ clang++ main.cc -fsanitize=memory -fsanitize-memory-track-origins -fno-omit-frame-pointer -Ljemalloc-build/lib -ljemalloc -fno-omit-frame-pointer -g -O2 -Ijemalloc-build/include
$ ./a.out
Segmentation fault
$ gdb ./a.out
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
...
Reading symbols from ./a.out...done.
(gdb) run
Starting program: /go/src/github.com/cockroachdb/cockroach/a.out
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000049b595 in calloc (num=num@entry=1, size=size@entry=32)
    at ../c-deps/jemalloc.src/src/jemalloc.c:1799
1799	{
(gdb) backtrace
#0  0x000000000049b595 in calloc (num=num@entry=1, size=size@entry=32)
    at ../c-deps/jemalloc.src/src/jemalloc.c:1799
#1  0x00007ffff7124627 in _dlerror_run (
    operate=operate@entry=0x7ffff7124020 <dlsym_doit>, args=args@entry=0x7fffffffeb20)
    at dlerror.c:141
#2  0x00007ffff7124088 in __dlsym (handle=<optimized out>, name=<optimized out>)
    at dlsym.c:70
#3  0x000000000047dfa7 in __sanitizer::InitTlsSize() ()
#4  0x000000000041b7ca in __msan_init ()
#5  0x0000000000422595 in __interceptor___cxa_atexit ()
#6  0x00007ffff7adee56 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7de74ea in call_init (l=<optimized out>, argc=argc@entry=1,
    argv=argv@entry=0x7fffffffec48, env=env@entry=0x7fffffffec58) at dl-init.c:72
#8  0x00007ffff7de75fb in call_init (env=0x7fffffffec58, argv=0x7fffffffec48, argc=1,
    l=<optimized out>) at dl-init.c:30
#9  _dl_init (main_map=0x7ffff7ffe168, argc=1, argv=0x7fffffffec48, env=0x7fffffffec58)
    at dl-init.c:120
#10 0x00007ffff7dd7cfa in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#11 0x0000000000000001 in ?? ()
#12 0x00007fffffffee2b in ?? ()
#13 0x0000000000000000 in ?? ()
(gdb) quit
```

```
$ clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by jasone** [comment]
MSan provides a custom allocator, which doesn't interoperate with other allocators.  It may be possible to build jemalloc with ```--with-jemalloc-prefix``` and run it under MSan, but no one has tried this to my knowledge.

**Comment by tamird** [comment]
> MSan provides a custom allocator, which doesn't interoperate with other allocators.

Is this documented anywhere? Why does this manifest as a crash? I think there's a tiny bit of investigation to be done here, even if the outcome remains to declare this configuration unsupported.

**Comment by jasone** [comment]
See https://github.com/google/sanitizers/wiki/AddressSanitizer, which is closely related to https://github.com/google/sanitizers/wiki/MemorySanitizer:

> The tool consists of a compiler instrumentation module (currently, an LLVM pass) and a run-time library which replaces the malloc function.

If you want to understand in more detail why the sanitizers replace malloc (and why jemalloc cannot replace *that* malloc), read more about the sanitizer technology.
